// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// HolidayService is an autogenerated mock type for the HolidayService type
type HolidayService struct {
	mock.Mock
}

type HolidayService_Expecter struct {
	mock *mock.Mock
}

func (_m *HolidayService) EXPECT() *HolidayService_Expecter {
	return &HolidayService_Expecter{mock: &_m.Mock}
}

// AddHoliday provides a mock function with given fields: ctx, role, adminID, date, desc
func (_m *HolidayService) AddHoliday(ctx context.Context, role string, adminID int64, date time.Time, desc string) error {
	ret := _m.Called(ctx, role, adminID, date, desc)

	if len(ret) == 0 {
		panic("no return value specified for AddHoliday")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, time.Time, string) error); ok {
		r0 = rf(ctx, role, adminID, date, desc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HolidayService_AddHoliday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddHoliday'
type HolidayService_AddHoliday_Call struct {
	*mock.Call
}

// AddHoliday is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - adminID int64
//   - date time.Time
//   - desc string
func (_e *HolidayService_Expecter) AddHoliday(ctx interface{}, role interface{}, adminID interface{}, date interface{}, desc interface{}) *HolidayService_AddHoliday_Call {
	return &HolidayService_AddHoliday_Call{Call: _e.mock.On("AddHoliday", ctx, role, adminID, date, desc)}
}

func (_c *HolidayService_AddHoliday_Call) Run(run func(ctx context.Context, role string, adminID int64, date time.Time, desc string)) *HolidayService_AddHoliday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(time.Time), args[4].(string))
	})
	return _c
}

func (_c *HolidayService_AddHoliday_Call) Return(_a0 error) *HolidayService_AddHoliday_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HolidayService_AddHoliday_Call) RunAndReturn(run func(context.Context, string, int64, time.Time, string) error) *HolidayService_AddHoliday_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteHoliday provides a mock function with given fields: ctx, role, holidayID
func (_m *HolidayService) DeleteHoliday(ctx context.Context, role string, holidayID int64) error {
	ret := _m.Called(ctx, role, holidayID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteHoliday")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, role, holidayID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HolidayService_DeleteHoliday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteHoliday'
type HolidayService_DeleteHoliday_Call struct {
	*mock.Call
}

// DeleteHoliday is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - holidayID int64
func (_e *HolidayService_Expecter) DeleteHoliday(ctx interface{}, role interface{}, holidayID interface{}) *HolidayService_DeleteHoliday_Call {
	return &HolidayService_DeleteHoliday_Call{Call: _e.mock.On("DeleteHoliday", ctx, role, holidayID)}
}

func (_c *HolidayService_DeleteHoliday_Call) Run(run func(ctx context.Context, role string, holidayID int64)) *HolidayService_DeleteHoliday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *HolidayService_DeleteHoliday_Call) Return(_a0 error) *HolidayService_DeleteHoliday_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HolidayService_DeleteHoliday_Call) RunAndReturn(run func(context.Context, string, int64) error) *HolidayService_DeleteHoliday_Call {
	_c.Call.Return(run)
	return _c
}

// GetHolidays provides a mock function with given fields: ctx, role
func (_m *HolidayService) GetHolidays(ctx context.Context, role string) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for GetHolidays")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]map[string]interface{}, error)); ok {
		return rf(ctx, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []map[string]interface{}); ok {
		r0 = rf(ctx, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HolidayService_GetHolidays_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHolidays'
type HolidayService_GetHolidays_Call struct {
	*mock.Call
}

// GetHolidays is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
func (_e *HolidayService_Expecter) GetHolidays(ctx interface{}, role interface{}) *HolidayService_GetHolidays_Call {
	return &HolidayService_GetHolidays_Call{Call: _e.mock.On("GetHolidays", ctx, role)}
}

func (_c *HolidayService_GetHolidays_Call) Run(run func(ctx context.Context, role string)) *HolidayService_GetHolidays_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *HolidayService_GetHolidays_Call) Return(_a0 []map[string]interface{}, _a1 error) *HolidayService_GetHolidays_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HolidayService_GetHolidays_Call) RunAndReturn(run func(context.Context, string) ([]map[string]interface{}, error)) *HolidayService_GetHolidays_Call {
	_c.Call.Return(run)
	return _c
}

// NewHolidayService creates a new instance of HolidayService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHolidayService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HolidayService {
	mock := &HolidayService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
