// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ExpenseApprovalService is an autogenerated mock type for the ExpenseApprovalService type
type ExpenseApprovalService struct {
	mock.Mock
}

type ExpenseApprovalService_Expecter struct {
	mock *mock.Mock
}

func (_m *ExpenseApprovalService) EXPECT() *ExpenseApprovalService_Expecter {
	return &ExpenseApprovalService_Expecter{mock: &_m.Mock}
}

// ApproveExpense provides a mock function with given fields: ctx, role, approverID, requestID, comment
func (_m *ExpenseApprovalService) ApproveExpense(ctx context.Context, role string, approverID int64, requestID int64, comment string) error {
	ret := _m.Called(ctx, role, approverID, requestID, comment)

	if len(ret) == 0 {
		panic("no return value specified for ApproveExpense")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) error); ok {
		r0 = rf(ctx, role, approverID, requestID, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpenseApprovalService_ApproveExpense_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveExpense'
type ExpenseApprovalService_ApproveExpense_Call struct {
	*mock.Call
}

// ApproveExpense is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - approverID int64
//   - requestID int64
//   - comment string
func (_e *ExpenseApprovalService_Expecter) ApproveExpense(ctx interface{}, role interface{}, approverID interface{}, requestID interface{}, comment interface{}) *ExpenseApprovalService_ApproveExpense_Call {
	return &ExpenseApprovalService_ApproveExpense_Call{Call: _e.mock.On("ApproveExpense", ctx, role, approverID, requestID, comment)}
}

func (_c *ExpenseApprovalService_ApproveExpense_Call) Run(run func(ctx context.Context, role string, approverID int64, requestID int64, comment string)) *ExpenseApprovalService_ApproveExpense_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *ExpenseApprovalService_ApproveExpense_Call) Return(_a0 error) *ExpenseApprovalService_ApproveExpense_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExpenseApprovalService_ApproveExpense_Call) RunAndReturn(run func(context.Context, string, int64, int64, string) error) *ExpenseApprovalService_ApproveExpense_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingExpenseRequests provides a mock function with given fields: ctx, role, approverID
func (_m *ExpenseApprovalService) GetPendingExpenseRequests(ctx context.Context, role string, approverID int64) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, role, approverID)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingExpenseRequests")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]map[string]interface{}, error)); ok {
		return rf(ctx, role, approverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []map[string]interface{}); ok {
		r0 = rf(ctx, role, approverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, role, approverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpenseApprovalService_GetPendingExpenseRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingExpenseRequests'
type ExpenseApprovalService_GetPendingExpenseRequests_Call struct {
	*mock.Call
}

// GetPendingExpenseRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - approverID int64
func (_e *ExpenseApprovalService_Expecter) GetPendingExpenseRequests(ctx interface{}, role interface{}, approverID interface{}) *ExpenseApprovalService_GetPendingExpenseRequests_Call {
	return &ExpenseApprovalService_GetPendingExpenseRequests_Call{Call: _e.mock.On("GetPendingExpenseRequests", ctx, role, approverID)}
}

func (_c *ExpenseApprovalService_GetPendingExpenseRequests_Call) Run(run func(ctx context.Context, role string, approverID int64)) *ExpenseApprovalService_GetPendingExpenseRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *ExpenseApprovalService_GetPendingExpenseRequests_Call) Return(_a0 []map[string]interface{}, _a1 error) *ExpenseApprovalService_GetPendingExpenseRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExpenseApprovalService_GetPendingExpenseRequests_Call) RunAndReturn(run func(context.Context, string, int64) ([]map[string]interface{}, error)) *ExpenseApprovalService_GetPendingExpenseRequests_Call {
	_c.Call.Return(run)
	return _c
}

// RejectExpense provides a mock function with given fields: ctx, role, approverID, requestID, comment
func (_m *ExpenseApprovalService) RejectExpense(ctx context.Context, role string, approverID int64, requestID int64, comment string) error {
	ret := _m.Called(ctx, role, approverID, requestID, comment)

	if len(ret) == 0 {
		panic("no return value specified for RejectExpense")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) error); ok {
		r0 = rf(ctx, role, approverID, requestID, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpenseApprovalService_RejectExpense_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectExpense'
type ExpenseApprovalService_RejectExpense_Call struct {
	*mock.Call
}

// RejectExpense is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - approverID int64
//   - requestID int64
//   - comment string
func (_e *ExpenseApprovalService_Expecter) RejectExpense(ctx interface{}, role interface{}, approverID interface{}, requestID interface{}, comment interface{}) *ExpenseApprovalService_RejectExpense_Call {
	return &ExpenseApprovalService_RejectExpense_Call{Call: _e.mock.On("RejectExpense", ctx, role, approverID, requestID, comment)}
}

func (_c *ExpenseApprovalService_RejectExpense_Call) Run(run func(ctx context.Context, role string, approverID int64, requestID int64, comment string)) *ExpenseApprovalService_RejectExpense_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *ExpenseApprovalService_RejectExpense_Call) Return(_a0 error) *ExpenseApprovalService_RejectExpense_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExpenseApprovalService_RejectExpense_Call) RunAndReturn(run func(context.Context, string, int64, int64, string) error) *ExpenseApprovalService_RejectExpense_Call {
	_c.Call.Return(run)
	return _c
}

// NewExpenseApprovalService creates a new instance of ExpenseApprovalService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpenseApprovalService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpenseApprovalService {
	mock := &ExpenseApprovalService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
