// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DiscountService is an autogenerated mock type for the DiscountService type
type DiscountService struct {
	mock.Mock
}

type DiscountService_Expecter struct {
	mock *mock.Mock
}

func (_m *DiscountService) EXPECT() *DiscountService_Expecter {
	return &DiscountService_Expecter{mock: &_m.Mock}
}

// ApplyDiscount provides a mock function with given fields: ctx, userID, percent, reason
func (_m *DiscountService) ApplyDiscount(ctx context.Context, userID int64, percent float64, reason string) (string, string, error) {
	ret := _m.Called(ctx, userID, percent, reason)

	if len(ret) == 0 {
		panic("no return value specified for ApplyDiscount")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, float64, string) (string, string, error)); ok {
		return rf(ctx, userID, percent, reason)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, float64, string) string); ok {
		r0 = rf(ctx, userID, percent, reason)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, float64, string) string); ok {
		r1 = rf(ctx, userID, percent, reason)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, float64, string) error); ok {
		r2 = rf(ctx, userID, percent, reason)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DiscountService_ApplyDiscount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyDiscount'
type DiscountService_ApplyDiscount_Call struct {
	*mock.Call
}

// ApplyDiscount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - percent float64
//   - reason string
func (_e *DiscountService_Expecter) ApplyDiscount(ctx interface{}, userID interface{}, percent interface{}, reason interface{}) *DiscountService_ApplyDiscount_Call {
	return &DiscountService_ApplyDiscount_Call{Call: _e.mock.On("ApplyDiscount", ctx, userID, percent, reason)}
}

func (_c *DiscountService_ApplyDiscount_Call) Run(run func(ctx context.Context, userID int64, percent float64, reason string)) *DiscountService_ApplyDiscount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(float64), args[3].(string))
	})
	return _c
}

func (_c *DiscountService_ApplyDiscount_Call) Return(_a0 string, _a1 string, _a2 error) *DiscountService_ApplyDiscount_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *DiscountService_ApplyDiscount_Call) RunAndReturn(run func(context.Context, int64, float64, string) (string, string, error)) *DiscountService_ApplyDiscount_Call {
	_c.Call.Return(run)
	return _c
}

// CancelDiscount provides a mock function with given fields: ctx, userID, requestID
func (_m *DiscountService) CancelDiscount(ctx context.Context, userID int64, requestID int64) error {
	ret := _m.Called(ctx, userID, requestID)

	if len(ret) == 0 {
		panic("no return value specified for CancelDiscount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DiscountService_CancelDiscount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelDiscount'
type DiscountService_CancelDiscount_Call struct {
	*mock.Call
}

// CancelDiscount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - requestID int64
func (_e *DiscountService_Expecter) CancelDiscount(ctx interface{}, userID interface{}, requestID interface{}) *DiscountService_CancelDiscount_Call {
	return &DiscountService_CancelDiscount_Call{Call: _e.mock.On("CancelDiscount", ctx, userID, requestID)}
}

func (_c *DiscountService_CancelDiscount_Call) Run(run func(ctx context.Context, userID int64, requestID int64)) *DiscountService_CancelDiscount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *DiscountService_CancelDiscount_Call) Return(_a0 error) *DiscountService_CancelDiscount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DiscountService_CancelDiscount_Call) RunAndReturn(run func(context.Context, int64, int64) error) *DiscountService_CancelDiscount_Call {
	_c.Call.Return(run)
	return _c
}

// NewDiscountService creates a new instance of DiscountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiscountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DiscountService {
	mock := &DiscountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
