// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// LoginUser provides a mock function with given fields: ctx, email, password
func (_m *AuthService) LoginUser(ctx context.Context, email string, password string) (string, string, error) {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for LoginUser")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, string, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, email, password)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AuthService_LoginUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoginUser'
type AuthService_LoginUser_Call struct {
	*mock.Call
}

// LoginUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *AuthService_Expecter) LoginUser(ctx interface{}, email interface{}, password interface{}) *AuthService_LoginUser_Call {
	return &AuthService_LoginUser_Call{Call: _e.mock.On("LoginUser", ctx, email, password)}
}

func (_c *AuthService_LoginUser_Call) Run(run func(ctx context.Context, email string, password string)) *AuthService_LoginUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuthService_LoginUser_Call) Return(_a0 string, _a1 string, _a2 error) *AuthService_LoginUser_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *AuthService_LoginUser_Call) RunAndReturn(run func(context.Context, string, string) (string, string, error)) *AuthService_LoginUser_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function with given fields: ctx, name, email, password
func (_m *AuthService) RegisterUser(ctx context.Context, name string, email string, password string) error {
	ret := _m.Called(ctx, name, email, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, name, email, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthService_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type AuthService_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - email string
//   - password string
func (_e *AuthService_Expecter) RegisterUser(ctx interface{}, name interface{}, email interface{}, password interface{}) *AuthService_RegisterUser_Call {
	return &AuthService_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, name, email, password)}
}

func (_c *AuthService_RegisterUser_Call) Run(run func(ctx context.Context, name string, email string, password string)) *AuthService_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *AuthService_RegisterUser_Call) Return(_a0 error) *AuthService_RegisterUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthService_RegisterUser_Call) RunAndReturn(run func(context.Context, string, string, string) error) *AuthService_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
