// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ExpenseService is an autogenerated mock type for the ExpenseService type
type ExpenseService struct {
	mock.Mock
}

type ExpenseService_Expecter struct {
	mock *mock.Mock
}

func (_m *ExpenseService) EXPECT() *ExpenseService_Expecter {
	return &ExpenseService_Expecter{mock: &_m.Mock}
}

// ApplyExpense provides a mock function with given fields: ctx, userID, amount, category, reason
func (_m *ExpenseService) ApplyExpense(ctx context.Context, userID int64, amount float64, category string, reason string) (string, string, error) {
	ret := _m.Called(ctx, userID, amount, category, reason)

	if len(ret) == 0 {
		panic("no return value specified for ApplyExpense")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, float64, string, string) (string, string, error)); ok {
		return rf(ctx, userID, amount, category, reason)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, float64, string, string) string); ok {
		r0 = rf(ctx, userID, amount, category, reason)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, float64, string, string) string); ok {
		r1 = rf(ctx, userID, amount, category, reason)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, float64, string, string) error); ok {
		r2 = rf(ctx, userID, amount, category, reason)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ExpenseService_ApplyExpense_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyExpense'
type ExpenseService_ApplyExpense_Call struct {
	*mock.Call
}

// ApplyExpense is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - amount float64
//   - category string
//   - reason string
func (_e *ExpenseService_Expecter) ApplyExpense(ctx interface{}, userID interface{}, amount interface{}, category interface{}, reason interface{}) *ExpenseService_ApplyExpense_Call {
	return &ExpenseService_ApplyExpense_Call{Call: _e.mock.On("ApplyExpense", ctx, userID, amount, category, reason)}
}

func (_c *ExpenseService_ApplyExpense_Call) Run(run func(ctx context.Context, userID int64, amount float64, category string, reason string)) *ExpenseService_ApplyExpense_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(float64), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *ExpenseService_ApplyExpense_Call) Return(_a0 string, _a1 string, _a2 error) *ExpenseService_ApplyExpense_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ExpenseService_ApplyExpense_Call) RunAndReturn(run func(context.Context, int64, float64, string, string) (string, string, error)) *ExpenseService_ApplyExpense_Call {
	_c.Call.Return(run)
	return _c
}

// CancelExpense provides a mock function with given fields: ctx, userID, requestID
func (_m *ExpenseService) CancelExpense(ctx context.Context, userID int64, requestID int64) error {
	ret := _m.Called(ctx, userID, requestID)

	if len(ret) == 0 {
		panic("no return value specified for CancelExpense")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpenseService_CancelExpense_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelExpense'
type ExpenseService_CancelExpense_Call struct {
	*mock.Call
}

// CancelExpense is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - requestID int64
func (_e *ExpenseService_Expecter) CancelExpense(ctx interface{}, userID interface{}, requestID interface{}) *ExpenseService_CancelExpense_Call {
	return &ExpenseService_CancelExpense_Call{Call: _e.mock.On("CancelExpense", ctx, userID, requestID)}
}

func (_c *ExpenseService_CancelExpense_Call) Run(run func(ctx context.Context, userID int64, requestID int64)) *ExpenseService_CancelExpense_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *ExpenseService_CancelExpense_Call) Return(_a0 error) *ExpenseService_CancelExpense_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExpenseService_CancelExpense_Call) RunAndReturn(run func(context.Context, int64, int64) error) *ExpenseService_CancelExpense_Call {
	_c.Call.Return(run)
	return _c
}

// NewExpenseService creates a new instance of ExpenseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpenseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpenseService {
	mock := &ExpenseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
