// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "github.com/ankita-advitot/rule_based_approval_engine/interfaces"
	mock "github.com/stretchr/testify/mock"

	models "github.com/ankita-advitot/rule_based_approval_engine/models"

	time "time"
)

// ExpenseRequestRepository is an autogenerated mock type for the ExpenseRequestRepository type
type ExpenseRequestRepository struct {
	mock.Mock
}

type ExpenseRequestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ExpenseRequestRepository) EXPECT() *ExpenseRequestRepository_Expecter {
	return &ExpenseRequestRepository_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, tx, requestID
func (_m *ExpenseRequestRepository) Cancel(ctx context.Context, tx interfaces.Tx, requestID int64) error {
	ret := _m.Called(ctx, tx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) error); ok {
		r0 = rf(ctx, tx, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpenseRequestRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type ExpenseRequestRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - requestID int64
func (_e *ExpenseRequestRepository_Expecter) Cancel(ctx interface{}, tx interface{}, requestID interface{}) *ExpenseRequestRepository_Cancel_Call {
	return &ExpenseRequestRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, tx, requestID)}
}

func (_c *ExpenseRequestRepository_Cancel_Call) Run(run func(ctx context.Context, tx interfaces.Tx, requestID int64)) *ExpenseRequestRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64))
	})
	return _c
}

func (_c *ExpenseRequestRepository_Cancel_Call) Return(_a0 error) *ExpenseRequestRepository_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExpenseRequestRepository_Cancel_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64) error) *ExpenseRequestRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, tx, req
func (_m *ExpenseRequestRepository) Create(ctx context.Context, tx interfaces.Tx, req *models.ExpenseRequest) error {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, *models.ExpenseRequest) error); ok {
		r0 = rf(ctx, tx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpenseRequestRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ExpenseRequestRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - req *models.ExpenseRequest
func (_e *ExpenseRequestRepository_Expecter) Create(ctx interface{}, tx interface{}, req interface{}) *ExpenseRequestRepository_Create_Call {
	return &ExpenseRequestRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, req)}
}

func (_c *ExpenseRequestRepository_Create_Call) Run(run func(ctx context.Context, tx interfaces.Tx, req *models.ExpenseRequest)) *ExpenseRequestRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(*models.ExpenseRequest))
	})
	return _c
}

func (_c *ExpenseRequestRepository_Create_Call) Return(_a0 error) *ExpenseRequestRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExpenseRequestRepository_Create_Call) RunAndReturn(run func(context.Context, interfaces.Tx, *models.ExpenseRequest) error) *ExpenseRequestRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, tx, requestID
func (_m *ExpenseRequestRepository) GetByID(ctx context.Context, tx interfaces.Tx, requestID int64) (*models.ExpenseRequest, error) {
	ret := _m.Called(ctx, tx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.ExpenseRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) (*models.ExpenseRequest, error)); ok {
		return rf(ctx, tx, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) *models.ExpenseRequest); ok {
		r0 = rf(ctx, tx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ExpenseRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.Tx, int64) error); ok {
		r1 = rf(ctx, tx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpenseRequestRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ExpenseRequestRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - requestID int64
func (_e *ExpenseRequestRepository_Expecter) GetByID(ctx interface{}, tx interface{}, requestID interface{}) *ExpenseRequestRepository_GetByID_Call {
	return &ExpenseRequestRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, tx, requestID)}
}

func (_c *ExpenseRequestRepository_GetByID_Call) Run(run func(ctx context.Context, tx interfaces.Tx, requestID int64)) *ExpenseRequestRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64))
	})
	return _c
}

func (_c *ExpenseRequestRepository_GetByID_Call) Return(_a0 *models.ExpenseRequest, _a1 error) *ExpenseRequestRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExpenseRequestRepository_GetByID_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64) (*models.ExpenseRequest, error)) *ExpenseRequestRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingForAdmin provides a mock function with given fields: ctx, limit, offset
func (_m *ExpenseRequestRepository) GetPendingForAdmin(ctx context.Context, limit int, offset int) ([]map[string]interface{}, int, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingForAdmin")
	}

	var r0 []map[string]interface{}
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]map[string]interface{}, int, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []map[string]interface{}); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ExpenseRequestRepository_GetPendingForAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingForAdmin'
type ExpenseRequestRepository_GetPendingForAdmin_Call struct {
	*mock.Call
}

// GetPendingForAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *ExpenseRequestRepository_Expecter) GetPendingForAdmin(ctx interface{}, limit interface{}, offset interface{}) *ExpenseRequestRepository_GetPendingForAdmin_Call {
	return &ExpenseRequestRepository_GetPendingForAdmin_Call{Call: _e.mock.On("GetPendingForAdmin", ctx, limit, offset)}
}

func (_c *ExpenseRequestRepository_GetPendingForAdmin_Call) Run(run func(ctx context.Context, limit int, offset int)) *ExpenseRequestRepository_GetPendingForAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *ExpenseRequestRepository_GetPendingForAdmin_Call) Return(_a0 []map[string]interface{}, _a1 int, _a2 error) *ExpenseRequestRepository_GetPendingForAdmin_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ExpenseRequestRepository_GetPendingForAdmin_Call) RunAndReturn(run func(context.Context, int, int) ([]map[string]interface{}, int, error)) *ExpenseRequestRepository_GetPendingForAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingForManager provides a mock function with given fields: ctx, managerID, limit, offset
func (_m *ExpenseRequestRepository) GetPendingForManager(ctx context.Context, managerID int64, limit int, offset int) ([]map[string]interface{}, int, error) {
	ret := _m.Called(ctx, managerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingForManager")
	}

	var r0 []map[string]interface{}
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) ([]map[string]interface{}, int, error)); ok {
		return rf(ctx, managerID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) []map[string]interface{}); ok {
		r0 = rf(ctx, managerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int) int); ok {
		r1 = rf(ctx, managerID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, int, int) error); ok {
		r2 = rf(ctx, managerID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ExpenseRequestRepository_GetPendingForManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingForManager'
type ExpenseRequestRepository_GetPendingForManager_Call struct {
	*mock.Call
}

// GetPendingForManager is a helper method to define mock.On call
//   - ctx context.Context
//   - managerID int64
//   - limit int
//   - offset int
func (_e *ExpenseRequestRepository_Expecter) GetPendingForManager(ctx interface{}, managerID interface{}, limit interface{}, offset interface{}) *ExpenseRequestRepository_GetPendingForManager_Call {
	return &ExpenseRequestRepository_GetPendingForManager_Call{Call: _e.mock.On("GetPendingForManager", ctx, managerID, limit, offset)}
}

func (_c *ExpenseRequestRepository_GetPendingForManager_Call) Run(run func(ctx context.Context, managerID int64, limit int, offset int)) *ExpenseRequestRepository_GetPendingForManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *ExpenseRequestRepository_GetPendingForManager_Call) Return(_a0 []map[string]interface{}, _a1 int, _a2 error) *ExpenseRequestRepository_GetPendingForManager_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ExpenseRequestRepository_GetPendingForManager_Call) RunAndReturn(run func(context.Context, int64, int, int) ([]map[string]interface{}, int, error)) *ExpenseRequestRepository_GetPendingForManager_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingRequests provides a mock function with given fields: ctx
func (_m *ExpenseRequestRepository) GetPendingRequests(ctx context.Context) ([]struct {
	ID        int64
	CreatedAt time.Time
}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingRequests")
	}

	var r0 []struct {
		ID        int64
		CreatedAt time.Time
	}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]struct {
		ID        int64
		CreatedAt time.Time
	}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []struct {
		ID        int64
		CreatedAt time.Time
	}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]struct {
				ID        int64
				CreatedAt time.Time
			})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpenseRequestRepository_GetPendingRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingRequests'
type ExpenseRequestRepository_GetPendingRequests_Call struct {
	*mock.Call
}

// GetPendingRequests is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ExpenseRequestRepository_Expecter) GetPendingRequests(ctx interface{}) *ExpenseRequestRepository_GetPendingRequests_Call {
	return &ExpenseRequestRepository_GetPendingRequests_Call{Call: _e.mock.On("GetPendingRequests", ctx)}
}

func (_c *ExpenseRequestRepository_GetPendingRequests_Call) Run(run func(ctx context.Context)) *ExpenseRequestRepository_GetPendingRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ExpenseRequestRepository_GetPendingRequests_Call) Return(_a0 []struct {
	ID        int64
	CreatedAt time.Time
}, _a1 error) *ExpenseRequestRepository_GetPendingRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExpenseRequestRepository_GetPendingRequests_Call) RunAndReturn(run func(context.Context) ([]struct {
	ID        int64
	CreatedAt time.Time
}, error)) *ExpenseRequestRepository_GetPendingRequests_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, tx, requestID, status, approverID, comment
func (_m *ExpenseRequestRepository) UpdateStatus(ctx context.Context, tx interfaces.Tx, requestID int64, status string, approverID int64, comment string) error {
	ret := _m.Called(ctx, tx, requestID, status, approverID, comment)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64, string, int64, string) error); ok {
		r0 = rf(ctx, tx, requestID, status, approverID, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExpenseRequestRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type ExpenseRequestRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - requestID int64
//   - status string
//   - approverID int64
//   - comment string
func (_e *ExpenseRequestRepository_Expecter) UpdateStatus(ctx interface{}, tx interface{}, requestID interface{}, status interface{}, approverID interface{}, comment interface{}) *ExpenseRequestRepository_UpdateStatus_Call {
	return &ExpenseRequestRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, tx, requestID, status, approverID, comment)}
}

func (_c *ExpenseRequestRepository_UpdateStatus_Call) Run(run func(ctx context.Context, tx interfaces.Tx, requestID int64, status string, approverID int64, comment string)) *ExpenseRequestRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64), args[3].(string), args[4].(int64), args[5].(string))
	})
	return _c
}

func (_c *ExpenseRequestRepository_UpdateStatus_Call) Return(_a0 error) *ExpenseRequestRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExpenseRequestRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64, string, int64, string) error) *ExpenseRequestRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewExpenseRequestRepository creates a new instance of ExpenseRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpenseRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpenseRequestRepository {
	mock := &ExpenseRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
