// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "github.com/ankita-advitot/rule_based_approval_engine/interfaces"
	mock "github.com/stretchr/testify/mock"

	models "github.com/ankita-advitot/rule_based_approval_engine/models"

	time "time"
)

// LeaveRequestRepository is an autogenerated mock type for the LeaveRequestRepository type
type LeaveRequestRepository struct {
	mock.Mock
}

type LeaveRequestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *LeaveRequestRepository) EXPECT() *LeaveRequestRepository_Expecter {
	return &LeaveRequestRepository_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, tx, requestID
func (_m *LeaveRequestRepository) Cancel(ctx context.Context, tx interfaces.Tx, requestID int64) error {
	ret := _m.Called(ctx, tx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) error); ok {
		r0 = rf(ctx, tx, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LeaveRequestRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type LeaveRequestRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - requestID int64
func (_e *LeaveRequestRepository_Expecter) Cancel(ctx interface{}, tx interface{}, requestID interface{}) *LeaveRequestRepository_Cancel_Call {
	return &LeaveRequestRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, tx, requestID)}
}

func (_c *LeaveRequestRepository_Cancel_Call) Run(run func(ctx context.Context, tx interfaces.Tx, requestID int64)) *LeaveRequestRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64))
	})
	return _c
}

func (_c *LeaveRequestRepository_Cancel_Call) Return(_a0 error) *LeaveRequestRepository_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LeaveRequestRepository_Cancel_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64) error) *LeaveRequestRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// CheckOverlap provides a mock function with given fields: ctx, userID, fromDate, toDate
func (_m *LeaveRequestRepository) CheckOverlap(ctx context.Context, userID int64, fromDate time.Time, toDate time.Time) (bool, error) {
	ret := _m.Called(ctx, userID, fromDate, toDate)

	if len(ret) == 0 {
		panic("no return value specified for CheckOverlap")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) (bool, error)); ok {
		return rf(ctx, userID, fromDate, toDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) bool); ok {
		r0 = rf(ctx, userID, fromDate, toDate)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, fromDate, toDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LeaveRequestRepository_CheckOverlap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckOverlap'
type LeaveRequestRepository_CheckOverlap_Call struct {
	*mock.Call
}

// CheckOverlap is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - fromDate time.Time
//   - toDate time.Time
func (_e *LeaveRequestRepository_Expecter) CheckOverlap(ctx interface{}, userID interface{}, fromDate interface{}, toDate interface{}) *LeaveRequestRepository_CheckOverlap_Call {
	return &LeaveRequestRepository_CheckOverlap_Call{Call: _e.mock.On("CheckOverlap", ctx, userID, fromDate, toDate)}
}

func (_c *LeaveRequestRepository_CheckOverlap_Call) Run(run func(ctx context.Context, userID int64, fromDate time.Time, toDate time.Time)) *LeaveRequestRepository_CheckOverlap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *LeaveRequestRepository_CheckOverlap_Call) Return(_a0 bool, _a1 error) *LeaveRequestRepository_CheckOverlap_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LeaveRequestRepository_CheckOverlap_Call) RunAndReturn(run func(context.Context, int64, time.Time, time.Time) (bool, error)) *LeaveRequestRepository_CheckOverlap_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, tx, req
func (_m *LeaveRequestRepository) Create(ctx context.Context, tx interfaces.Tx, req *models.LeaveRequest) error {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, *models.LeaveRequest) error); ok {
		r0 = rf(ctx, tx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LeaveRequestRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type LeaveRequestRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - req *models.LeaveRequest
func (_e *LeaveRequestRepository_Expecter) Create(ctx interface{}, tx interface{}, req interface{}) *LeaveRequestRepository_Create_Call {
	return &LeaveRequestRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, req)}
}

func (_c *LeaveRequestRepository_Create_Call) Run(run func(ctx context.Context, tx interfaces.Tx, req *models.LeaveRequest)) *LeaveRequestRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(*models.LeaveRequest))
	})
	return _c
}

func (_c *LeaveRequestRepository_Create_Call) Return(_a0 error) *LeaveRequestRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LeaveRequestRepository_Create_Call) RunAndReturn(run func(context.Context, interfaces.Tx, *models.LeaveRequest) error) *LeaveRequestRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, tx, requestID
func (_m *LeaveRequestRepository) GetByID(ctx context.Context, tx interfaces.Tx, requestID int64) (*models.LeaveRequest, error) {
	ret := _m.Called(ctx, tx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.LeaveRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) (*models.LeaveRequest, error)); ok {
		return rf(ctx, tx, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) *models.LeaveRequest); ok {
		r0 = rf(ctx, tx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LeaveRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.Tx, int64) error); ok {
		r1 = rf(ctx, tx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LeaveRequestRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type LeaveRequestRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - requestID int64
func (_e *LeaveRequestRepository_Expecter) GetByID(ctx interface{}, tx interface{}, requestID interface{}) *LeaveRequestRepository_GetByID_Call {
	return &LeaveRequestRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, tx, requestID)}
}

func (_c *LeaveRequestRepository_GetByID_Call) Run(run func(ctx context.Context, tx interfaces.Tx, requestID int64)) *LeaveRequestRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64))
	})
	return _c
}

func (_c *LeaveRequestRepository_GetByID_Call) Return(_a0 *models.LeaveRequest, _a1 error) *LeaveRequestRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LeaveRequestRepository_GetByID_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64) (*models.LeaveRequest, error)) *LeaveRequestRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingForAdmin provides a mock function with given fields: ctx
func (_m *LeaveRequestRepository) GetPendingForAdmin(ctx context.Context) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingForAdmin")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]map[string]interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LeaveRequestRepository_GetPendingForAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingForAdmin'
type LeaveRequestRepository_GetPendingForAdmin_Call struct {
	*mock.Call
}

// GetPendingForAdmin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *LeaveRequestRepository_Expecter) GetPendingForAdmin(ctx interface{}) *LeaveRequestRepository_GetPendingForAdmin_Call {
	return &LeaveRequestRepository_GetPendingForAdmin_Call{Call: _e.mock.On("GetPendingForAdmin", ctx)}
}

func (_c *LeaveRequestRepository_GetPendingForAdmin_Call) Run(run func(ctx context.Context)) *LeaveRequestRepository_GetPendingForAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *LeaveRequestRepository_GetPendingForAdmin_Call) Return(_a0 []map[string]interface{}, _a1 error) *LeaveRequestRepository_GetPendingForAdmin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LeaveRequestRepository_GetPendingForAdmin_Call) RunAndReturn(run func(context.Context) ([]map[string]interface{}, error)) *LeaveRequestRepository_GetPendingForAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingForManager provides a mock function with given fields: ctx, managerID
func (_m *LeaveRequestRepository) GetPendingForManager(ctx context.Context, managerID int64) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, managerID)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingForManager")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]map[string]interface{}, error)); ok {
		return rf(ctx, managerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []map[string]interface{}); ok {
		r0 = rf(ctx, managerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, managerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LeaveRequestRepository_GetPendingForManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingForManager'
type LeaveRequestRepository_GetPendingForManager_Call struct {
	*mock.Call
}

// GetPendingForManager is a helper method to define mock.On call
//   - ctx context.Context
//   - managerID int64
func (_e *LeaveRequestRepository_Expecter) GetPendingForManager(ctx interface{}, managerID interface{}) *LeaveRequestRepository_GetPendingForManager_Call {
	return &LeaveRequestRepository_GetPendingForManager_Call{Call: _e.mock.On("GetPendingForManager", ctx, managerID)}
}

func (_c *LeaveRequestRepository_GetPendingForManager_Call) Run(run func(ctx context.Context, managerID int64)) *LeaveRequestRepository_GetPendingForManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *LeaveRequestRepository_GetPendingForManager_Call) Return(_a0 []map[string]interface{}, _a1 error) *LeaveRequestRepository_GetPendingForManager_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LeaveRequestRepository_GetPendingForManager_Call) RunAndReturn(run func(context.Context, int64) ([]map[string]interface{}, error)) *LeaveRequestRepository_GetPendingForManager_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingRequests provides a mock function with given fields: ctx
func (_m *LeaveRequestRepository) GetPendingRequests(ctx context.Context) ([]struct {
	ID        int64
	CreatedAt time.Time
}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingRequests")
	}

	var r0 []struct {
		ID        int64
		CreatedAt time.Time
	}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]struct {
		ID        int64
		CreatedAt time.Time
	}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []struct {
		ID        int64
		CreatedAt time.Time
	}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]struct {
				ID        int64
				CreatedAt time.Time
			})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LeaveRequestRepository_GetPendingRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingRequests'
type LeaveRequestRepository_GetPendingRequests_Call struct {
	*mock.Call
}

// GetPendingRequests is a helper method to define mock.On call
//   - ctx context.Context
func (_e *LeaveRequestRepository_Expecter) GetPendingRequests(ctx interface{}) *LeaveRequestRepository_GetPendingRequests_Call {
	return &LeaveRequestRepository_GetPendingRequests_Call{Call: _e.mock.On("GetPendingRequests", ctx)}
}

func (_c *LeaveRequestRepository_GetPendingRequests_Call) Run(run func(ctx context.Context)) *LeaveRequestRepository_GetPendingRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *LeaveRequestRepository_GetPendingRequests_Call) Return(_a0 []struct {
	ID        int64
	CreatedAt time.Time
}, _a1 error) *LeaveRequestRepository_GetPendingRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LeaveRequestRepository_GetPendingRequests_Call) RunAndReturn(run func(context.Context) ([]struct {
	ID        int64
	CreatedAt time.Time
}, error)) *LeaveRequestRepository_GetPendingRequests_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, tx, requestID, status, approverID, comment
func (_m *LeaveRequestRepository) UpdateStatus(ctx context.Context, tx interfaces.Tx, requestID int64, status string, approverID int64, comment string) error {
	ret := _m.Called(ctx, tx, requestID, status, approverID, comment)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64, string, int64, string) error); ok {
		r0 = rf(ctx, tx, requestID, status, approverID, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LeaveRequestRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type LeaveRequestRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - requestID int64
//   - status string
//   - approverID int64
//   - comment string
func (_e *LeaveRequestRepository_Expecter) UpdateStatus(ctx interface{}, tx interface{}, requestID interface{}, status interface{}, approverID interface{}, comment interface{}) *LeaveRequestRepository_UpdateStatus_Call {
	return &LeaveRequestRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, tx, requestID, status, approverID, comment)}
}

func (_c *LeaveRequestRepository_UpdateStatus_Call) Run(run func(ctx context.Context, tx interfaces.Tx, requestID int64, status string, approverID int64, comment string)) *LeaveRequestRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64), args[3].(string), args[4].(int64), args[5].(string))
	})
	return _c
}

func (_c *LeaveRequestRepository_UpdateStatus_Call) Return(_a0 error) *LeaveRequestRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LeaveRequestRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64, string, int64, string) error) *LeaveRequestRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewLeaveRequestRepository creates a new instance of LeaveRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaveRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaveRequestRepository {
	mock := &LeaveRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
