// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// LeaveApprovalService is an autogenerated mock type for the LeaveApprovalService type
type LeaveApprovalService struct {
	mock.Mock
}

type LeaveApprovalService_Expecter struct {
	mock *mock.Mock
}

func (_m *LeaveApprovalService) EXPECT() *LeaveApprovalService_Expecter {
	return &LeaveApprovalService_Expecter{mock: &_m.Mock}
}

// ApproveLeave provides a mock function with given fields: ctx, role, approverID, requestID, approvalComment
func (_m *LeaveApprovalService) ApproveLeave(ctx context.Context, role string, approverID int64, requestID int64, approvalComment string) error {
	ret := _m.Called(ctx, role, approverID, requestID, approvalComment)

	if len(ret) == 0 {
		panic("no return value specified for ApproveLeave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) error); ok {
		r0 = rf(ctx, role, approverID, requestID, approvalComment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LeaveApprovalService_ApproveLeave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveLeave'
type LeaveApprovalService_ApproveLeave_Call struct {
	*mock.Call
}

// ApproveLeave is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - approverID int64
//   - requestID int64
//   - approvalComment string
func (_e *LeaveApprovalService_Expecter) ApproveLeave(ctx interface{}, role interface{}, approverID interface{}, requestID interface{}, approvalComment interface{}) *LeaveApprovalService_ApproveLeave_Call {
	return &LeaveApprovalService_ApproveLeave_Call{Call: _e.mock.On("ApproveLeave", ctx, role, approverID, requestID, approvalComment)}
}

func (_c *LeaveApprovalService_ApproveLeave_Call) Run(run func(ctx context.Context, role string, approverID int64, requestID int64, approvalComment string)) *LeaveApprovalService_ApproveLeave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *LeaveApprovalService_ApproveLeave_Call) Return(_a0 error) *LeaveApprovalService_ApproveLeave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LeaveApprovalService_ApproveLeave_Call) RunAndReturn(run func(context.Context, string, int64, int64, string) error) *LeaveApprovalService_ApproveLeave_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingLeaveRequests provides a mock function with given fields: ctx, role, approverID, limit, offset
func (_m *LeaveApprovalService) GetPendingLeaveRequests(ctx context.Context, role string, approverID int64, limit int, offset int) ([]map[string]interface{}, int, error) {
	ret := _m.Called(ctx, role, approverID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingLeaveRequests")
	}

	var r0 []map[string]interface{}
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int, int) ([]map[string]interface{}, int, error)); ok {
		return rf(ctx, role, approverID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int, int) []map[string]interface{}); ok {
		r0 = rf(ctx, role, approverID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int, int) int); ok {
		r1 = rf(ctx, role, approverID, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int64, int, int) error); ok {
		r2 = rf(ctx, role, approverID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// LeaveApprovalService_GetPendingLeaveRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingLeaveRequests'
type LeaveApprovalService_GetPendingLeaveRequests_Call struct {
	*mock.Call
}

// GetPendingLeaveRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - approverID int64
//   - limit int
//   - offset int
func (_e *LeaveApprovalService_Expecter) GetPendingLeaveRequests(ctx interface{}, role interface{}, approverID interface{}, limit interface{}, offset interface{}) *LeaveApprovalService_GetPendingLeaveRequests_Call {
	return &LeaveApprovalService_GetPendingLeaveRequests_Call{Call: _e.mock.On("GetPendingLeaveRequests", ctx, role, approverID, limit, offset)}
}

func (_c *LeaveApprovalService_GetPendingLeaveRequests_Call) Run(run func(ctx context.Context, role string, approverID int64, limit int, offset int)) *LeaveApprovalService_GetPendingLeaveRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *LeaveApprovalService_GetPendingLeaveRequests_Call) Return(_a0 []map[string]interface{}, _a1 int, _a2 error) *LeaveApprovalService_GetPendingLeaveRequests_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *LeaveApprovalService_GetPendingLeaveRequests_Call) RunAndReturn(run func(context.Context, string, int64, int, int) ([]map[string]interface{}, int, error)) *LeaveApprovalService_GetPendingLeaveRequests_Call {
	_c.Call.Return(run)
	return _c
}

// RejectLeave provides a mock function with given fields: ctx, role, approverID, requestID, rejectionComment
func (_m *LeaveApprovalService) RejectLeave(ctx context.Context, role string, approverID int64, requestID int64, rejectionComment string) error {
	ret := _m.Called(ctx, role, approverID, requestID, rejectionComment)

	if len(ret) == 0 {
		panic("no return value specified for RejectLeave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) error); ok {
		r0 = rf(ctx, role, approverID, requestID, rejectionComment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LeaveApprovalService_RejectLeave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectLeave'
type LeaveApprovalService_RejectLeave_Call struct {
	*mock.Call
}

// RejectLeave is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - approverID int64
//   - requestID int64
//   - rejectionComment string
func (_e *LeaveApprovalService_Expecter) RejectLeave(ctx interface{}, role interface{}, approverID interface{}, requestID interface{}, rejectionComment interface{}) *LeaveApprovalService_RejectLeave_Call {
	return &LeaveApprovalService_RejectLeave_Call{Call: _e.mock.On("RejectLeave", ctx, role, approverID, requestID, rejectionComment)}
}

func (_c *LeaveApprovalService_RejectLeave_Call) Run(run func(ctx context.Context, role string, approverID int64, requestID int64, rejectionComment string)) *LeaveApprovalService_RejectLeave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *LeaveApprovalService_RejectLeave_Call) Return(_a0 error) *LeaveApprovalService_RejectLeave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LeaveApprovalService_RejectLeave_Call) RunAndReturn(run func(context.Context, string, int64, int64, string) error) *LeaveApprovalService_RejectLeave_Call {
	_c.Call.Return(run)
	return _c
}

// NewLeaveApprovalService creates a new instance of LeaveApprovalService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaveApprovalService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaveApprovalService {
	mock := &LeaveApprovalService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
