// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/ankita-advitot/rule_based_approval_engine/models"
)

// ReportService is an autogenerated mock type for the ReportService type
type ReportService struct {
	mock.Mock
}

type ReportService_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportService) EXPECT() *ReportService_Expecter {
	return &ReportService_Expecter{mock: &_m.Mock}
}

// GetDashboardSummary provides a mock function with given fields: ctx, role
func (_m *ReportService) GetDashboardSummary(ctx context.Context, role string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for GetDashboardSummary")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]interface{}, error)); ok {
		return rf(ctx, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]interface{}); ok {
		r0 = rf(ctx, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_GetDashboardSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDashboardSummary'
type ReportService_GetDashboardSummary_Call struct {
	*mock.Call
}

// GetDashboardSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
func (_e *ReportService_Expecter) GetDashboardSummary(ctx interface{}, role interface{}) *ReportService_GetDashboardSummary_Call {
	return &ReportService_GetDashboardSummary_Call{Call: _e.mock.On("GetDashboardSummary", ctx, role)}
}

func (_c *ReportService_GetDashboardSummary_Call) Run(run func(ctx context.Context, role string)) *ReportService_GetDashboardSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ReportService_GetDashboardSummary_Call) Return(_a0 map[string]interface{}, _a1 error) *ReportService_GetDashboardSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_GetDashboardSummary_Call) RunAndReturn(run func(context.Context, string) (map[string]interface{}, error)) *ReportService_GetDashboardSummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestStatusDistribution provides a mock function with given fields: ctx
func (_m *ReportService) GetRequestStatusDistribution(ctx context.Context) (map[string]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestStatusDistribution")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_GetRequestStatusDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestStatusDistribution'
type ReportService_GetRequestStatusDistribution_Call struct {
	*mock.Call
}

// GetRequestStatusDistribution is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReportService_Expecter) GetRequestStatusDistribution(ctx interface{}) *ReportService_GetRequestStatusDistribution_Call {
	return &ReportService_GetRequestStatusDistribution_Call{Call: _e.mock.On("GetRequestStatusDistribution", ctx)}
}

func (_c *ReportService_GetRequestStatusDistribution_Call) Run(run func(ctx context.Context)) *ReportService_GetRequestStatusDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReportService_GetRequestStatusDistribution_Call) Return(_a0 map[string]int, _a1 error) *ReportService_GetRequestStatusDistribution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_GetRequestStatusDistribution_Call) RunAndReturn(run func(context.Context) (map[string]int, error)) *ReportService_GetRequestStatusDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestsByTypeReport provides a mock function with given fields: ctx
func (_m *ReportService) GetRequestsByTypeReport(ctx context.Context) ([]models.RequestTypeReport, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestsByTypeReport")
	}

	var r0 []models.RequestTypeReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.RequestTypeReport, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.RequestTypeReport); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RequestTypeReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_GetRequestsByTypeReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestsByTypeReport'
type ReportService_GetRequestsByTypeReport_Call struct {
	*mock.Call
}

// GetRequestsByTypeReport is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReportService_Expecter) GetRequestsByTypeReport(ctx interface{}) *ReportService_GetRequestsByTypeReport_Call {
	return &ReportService_GetRequestsByTypeReport_Call{Call: _e.mock.On("GetRequestsByTypeReport", ctx)}
}

func (_c *ReportService_GetRequestsByTypeReport_Call) Run(run func(ctx context.Context)) *ReportService_GetRequestsByTypeReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReportService_GetRequestsByTypeReport_Call) Return(_a0 []models.RequestTypeReport, _a1 error) *ReportService_GetRequestsByTypeReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_GetRequestsByTypeReport_Call) RunAndReturn(run func(context.Context) ([]models.RequestTypeReport, error)) *ReportService_GetRequestsByTypeReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewReportService creates a new instance of ReportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportService {
	mock := &ReportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
