// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// BalanceService is an autogenerated mock type for the BalanceService type
type BalanceService struct {
	mock.Mock
}

type BalanceService_Expecter struct {
	mock *mock.Mock
}

func (_m *BalanceService) EXPECT() *BalanceService_Expecter {
	return &BalanceService_Expecter{mock: &_m.Mock}
}

// GetBalances provides a mock function with given fields: ctx, userID
func (_m *BalanceService) GetBalances(ctx context.Context, userID int64) (map[string]interface{}, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalances")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (map[string]interface{}, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) map[string]interface{}); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BalanceService_GetBalances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalances'
type BalanceService_GetBalances_Call struct {
	*mock.Call
}

// GetBalances is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *BalanceService_Expecter) GetBalances(ctx interface{}, userID interface{}) *BalanceService_GetBalances_Call {
	return &BalanceService_GetBalances_Call{Call: _e.mock.On("GetBalances", ctx, userID)}
}

func (_c *BalanceService_GetBalances_Call) Run(run func(ctx context.Context, userID int64)) *BalanceService_GetBalances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *BalanceService_GetBalances_Call) Return(_a0 map[string]interface{}, _a1 error) *BalanceService_GetBalances_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BalanceService_GetBalances_Call) RunAndReturn(run func(context.Context, int64) (map[string]interface{}, error)) *BalanceService_GetBalances_Call {
	_c.Call.Return(run)
	return _c
}

// NewBalanceService creates a new instance of BalanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceService {
	mock := &BalanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
