// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DiscountApprovalService is an autogenerated mock type for the DiscountApprovalService type
type DiscountApprovalService struct {
	mock.Mock
}

type DiscountApprovalService_Expecter struct {
	mock *mock.Mock
}

func (_m *DiscountApprovalService) EXPECT() *DiscountApprovalService_Expecter {
	return &DiscountApprovalService_Expecter{mock: &_m.Mock}
}

// ApproveDiscount provides a mock function with given fields: ctx, role, approverID, requestID, comment
func (_m *DiscountApprovalService) ApproveDiscount(ctx context.Context, role string, approverID int64, requestID int64, comment string) error {
	ret := _m.Called(ctx, role, approverID, requestID, comment)

	if len(ret) == 0 {
		panic("no return value specified for ApproveDiscount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) error); ok {
		r0 = rf(ctx, role, approverID, requestID, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DiscountApprovalService_ApproveDiscount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApproveDiscount'
type DiscountApprovalService_ApproveDiscount_Call struct {
	*mock.Call
}

// ApproveDiscount is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - approverID int64
//   - requestID int64
//   - comment string
func (_e *DiscountApprovalService_Expecter) ApproveDiscount(ctx interface{}, role interface{}, approverID interface{}, requestID interface{}, comment interface{}) *DiscountApprovalService_ApproveDiscount_Call {
	return &DiscountApprovalService_ApproveDiscount_Call{Call: _e.mock.On("ApproveDiscount", ctx, role, approverID, requestID, comment)}
}

func (_c *DiscountApprovalService_ApproveDiscount_Call) Run(run func(ctx context.Context, role string, approverID int64, requestID int64, comment string)) *DiscountApprovalService_ApproveDiscount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *DiscountApprovalService_ApproveDiscount_Call) Return(_a0 error) *DiscountApprovalService_ApproveDiscount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DiscountApprovalService_ApproveDiscount_Call) RunAndReturn(run func(context.Context, string, int64, int64, string) error) *DiscountApprovalService_ApproveDiscount_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingRequests provides a mock function with given fields: ctx, role, approverID
func (_m *DiscountApprovalService) GetPendingRequests(ctx context.Context, role string, approverID int64) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, role, approverID)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingRequests")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]map[string]interface{}, error)); ok {
		return rf(ctx, role, approverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []map[string]interface{}); ok {
		r0 = rf(ctx, role, approverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, role, approverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DiscountApprovalService_GetPendingRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingRequests'
type DiscountApprovalService_GetPendingRequests_Call struct {
	*mock.Call
}

// GetPendingRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - approverID int64
func (_e *DiscountApprovalService_Expecter) GetPendingRequests(ctx interface{}, role interface{}, approverID interface{}) *DiscountApprovalService_GetPendingRequests_Call {
	return &DiscountApprovalService_GetPendingRequests_Call{Call: _e.mock.On("GetPendingRequests", ctx, role, approverID)}
}

func (_c *DiscountApprovalService_GetPendingRequests_Call) Run(run func(ctx context.Context, role string, approverID int64)) *DiscountApprovalService_GetPendingRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *DiscountApprovalService_GetPendingRequests_Call) Return(_a0 []map[string]interface{}, _a1 error) *DiscountApprovalService_GetPendingRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DiscountApprovalService_GetPendingRequests_Call) RunAndReturn(run func(context.Context, string, int64) ([]map[string]interface{}, error)) *DiscountApprovalService_GetPendingRequests_Call {
	_c.Call.Return(run)
	return _c
}

// RejectDiscount provides a mock function with given fields: ctx, role, approverID, requestID, comment
func (_m *DiscountApprovalService) RejectDiscount(ctx context.Context, role string, approverID int64, requestID int64, comment string) error {
	ret := _m.Called(ctx, role, approverID, requestID, comment)

	if len(ret) == 0 {
		panic("no return value specified for RejectDiscount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) error); ok {
		r0 = rf(ctx, role, approverID, requestID, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DiscountApprovalService_RejectDiscount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RejectDiscount'
type DiscountApprovalService_RejectDiscount_Call struct {
	*mock.Call
}

// RejectDiscount is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - approverID int64
//   - requestID int64
//   - comment string
func (_e *DiscountApprovalService_Expecter) RejectDiscount(ctx interface{}, role interface{}, approverID interface{}, requestID interface{}, comment interface{}) *DiscountApprovalService_RejectDiscount_Call {
	return &DiscountApprovalService_RejectDiscount_Call{Call: _e.mock.On("RejectDiscount", ctx, role, approverID, requestID, comment)}
}

func (_c *DiscountApprovalService_RejectDiscount_Call) Run(run func(ctx context.Context, role string, approverID int64, requestID int64, comment string)) *DiscountApprovalService_RejectDiscount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *DiscountApprovalService_RejectDiscount_Call) Return(_a0 error) *DiscountApprovalService_RejectDiscount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DiscountApprovalService_RejectDiscount_Call) RunAndReturn(run func(context.Context, string, int64, int64, string) error) *DiscountApprovalService_RejectDiscount_Call {
	_c.Call.Return(run)
	return _c
}

// NewDiscountApprovalService creates a new instance of DiscountApprovalService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiscountApprovalService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DiscountApprovalService {
	mock := &DiscountApprovalService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
