// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "github.com/ankita-advitot/rule_based_approval_engine/interfaces"
	mock "github.com/stretchr/testify/mock"

	models "github.com/ankita-advitot/rule_based_approval_engine/models"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// CheckEmailExists provides a mock function with given fields: ctx, tx, email
func (_m *UserRepository) CheckEmailExists(ctx context.Context, tx interfaces.Tx, email string) (bool, error) {
	ret := _m.Called(ctx, tx, email)

	if len(ret) == 0 {
		panic("no return value specified for CheckEmailExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, string) (bool, error)); ok {
		return rf(ctx, tx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, string) bool); ok {
		r0 = rf(ctx, tx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.Tx, string) error); ok {
		r1 = rf(ctx, tx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_CheckEmailExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckEmailExists'
type UserRepository_CheckEmailExists_Call struct {
	*mock.Call
}

// CheckEmailExists is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - email string
func (_e *UserRepository_Expecter) CheckEmailExists(ctx interface{}, tx interface{}, email interface{}) *UserRepository_CheckEmailExists_Call {
	return &UserRepository_CheckEmailExists_Call{Call: _e.mock.On("CheckEmailExists", ctx, tx, email)}
}

func (_c *UserRepository_CheckEmailExists_Call) Run(run func(ctx context.Context, tx interfaces.Tx, email string)) *UserRepository_CheckEmailExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(string))
	})
	return _c
}

func (_c *UserRepository_CheckEmailExists_Call) Return(_a0 bool, _a1 error) *UserRepository_CheckEmailExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_CheckEmailExists_Call) RunAndReturn(run func(context.Context, interfaces.Tx, string) (bool, error)) *UserRepository_CheckEmailExists_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, tx, user
func (_m *UserRepository) Create(ctx context.Context, tx interfaces.Tx, user *models.User) (int64, error) {
	ret := _m.Called(ctx, tx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, *models.User) (int64, error)); ok {
		return rf(ctx, tx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, *models.User) int64); ok {
		r0 = rf(ctx, tx, user)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.Tx, *models.User) error); ok {
		r1 = rf(ctx, tx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - user *models.User
func (_e *UserRepository_Expecter) Create(ctx interface{}, tx interface{}, user interface{}) *UserRepository_Create_Call {
	return &UserRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, user)}
}

func (_c *UserRepository_Create_Call) Run(run func(ctx context.Context, tx interfaces.Tx, user *models.User)) *UserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(*models.User))
	})
	return _c
}

func (_c *UserRepository_Create_Call) Return(_a0 int64, _a1 error) *UserRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_Create_Call) RunAndReturn(run func(context.Context, interfaces.Tx, *models.User) (int64, error)) *UserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepository) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type UserRepository_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserRepository_Expecter) GetByEmail(ctx interface{}, email interface{}) *UserRepository_GetByEmail_Call {
	return &UserRepository_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *UserRepository_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *UserRepository_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserRepository_GetByEmail_Call) Return(_a0 *models.User, _a1 error) *UserRepository_GetByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetByEmail_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *UserRepository_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserRepository) GetByID(ctx context.Context, id int64) (*models.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UserRepository_Expecter) GetByID(ctx interface{}, id interface{}) *UserRepository_GetByID_Call {
	return &UserRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *UserRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *UserRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UserRepository_GetByID_Call) Return(_a0 *models.User, _a1 error) *UserRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*models.User, error)) *UserRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetGrade provides a mock function with given fields: ctx, tx, userID
func (_m *UserRepository) GetGrade(ctx context.Context, tx interfaces.Tx, userID int64) (int64, error) {
	ret := _m.Called(ctx, tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetGrade")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) (int64, error)); ok {
		return rf(ctx, tx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) int64); ok {
		r0 = rf(ctx, tx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.Tx, int64) error); ok {
		r1 = rf(ctx, tx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetGrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGrade'
type UserRepository_GetGrade_Call struct {
	*mock.Call
}

// GetGrade is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - userID int64
func (_e *UserRepository_Expecter) GetGrade(ctx interface{}, tx interface{}, userID interface{}) *UserRepository_GetGrade_Call {
	return &UserRepository_GetGrade_Call{Call: _e.mock.On("GetGrade", ctx, tx, userID)}
}

func (_c *UserRepository_GetGrade_Call) Run(run func(ctx context.Context, tx interfaces.Tx, userID int64)) *UserRepository_GetGrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64))
	})
	return _c
}

func (_c *UserRepository_GetGrade_Call) Return(_a0 int64, _a1 error) *UserRepository_GetGrade_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetGrade_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64) (int64, error)) *UserRepository_GetGrade_Call {
	_c.Call.Return(run)
	return _c
}

// GetRole provides a mock function with given fields: ctx, tx, userID
func (_m *UserRepository) GetRole(ctx context.Context, tx interfaces.Tx, userID int64) (string, error) {
	ret := _m.Called(ctx, tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetRole")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) (string, error)); ok {
		return rf(ctx, tx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) string); ok {
		r0 = rf(ctx, tx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.Tx, int64) error); ok {
		r1 = rf(ctx, tx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRole'
type UserRepository_GetRole_Call struct {
	*mock.Call
}

// GetRole is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - userID int64
func (_e *UserRepository_Expecter) GetRole(ctx interface{}, tx interface{}, userID interface{}) *UserRepository_GetRole_Call {
	return &UserRepository_GetRole_Call{Call: _e.mock.On("GetRole", ctx, tx, userID)}
}

func (_c *UserRepository_GetRole_Call) Run(run func(ctx context.Context, tx interfaces.Tx, userID int64)) *UserRepository_GetRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64))
	})
	return _c
}

func (_c *UserRepository_GetRole_Call) Return(_a0 string, _a1 error) *UserRepository_GetRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetRole_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64) (string, error)) *UserRepository_GetRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
