// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "github.com/ankita-advitot/rule_based_approval_engine/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// BalanceRepository is an autogenerated mock type for the BalanceRepository type
type BalanceRepository struct {
	mock.Mock
}

type BalanceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BalanceRepository) EXPECT() *BalanceRepository_Expecter {
	return &BalanceRepository_Expecter{mock: &_m.Mock}
}

// DeductDiscountBalance provides a mock function with given fields: ctx, tx, userID, percent
func (_m *BalanceRepository) DeductDiscountBalance(ctx context.Context, tx interfaces.Tx, userID int64, percent float64) error {
	ret := _m.Called(ctx, tx, userID, percent)

	if len(ret) == 0 {
		panic("no return value specified for DeductDiscountBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64, float64) error); ok {
		r0 = rf(ctx, tx, userID, percent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BalanceRepository_DeductDiscountBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeductDiscountBalance'
type BalanceRepository_DeductDiscountBalance_Call struct {
	*mock.Call
}

// DeductDiscountBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - userID int64
//   - percent float64
func (_e *BalanceRepository_Expecter) DeductDiscountBalance(ctx interface{}, tx interface{}, userID interface{}, percent interface{}) *BalanceRepository_DeductDiscountBalance_Call {
	return &BalanceRepository_DeductDiscountBalance_Call{Call: _e.mock.On("DeductDiscountBalance", ctx, tx, userID, percent)}
}

func (_c *BalanceRepository_DeductDiscountBalance_Call) Run(run func(ctx context.Context, tx interfaces.Tx, userID int64, percent float64)) *BalanceRepository_DeductDiscountBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64), args[3].(float64))
	})
	return _c
}

func (_c *BalanceRepository_DeductDiscountBalance_Call) Return(_a0 error) *BalanceRepository_DeductDiscountBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BalanceRepository_DeductDiscountBalance_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64, float64) error) *BalanceRepository_DeductDiscountBalance_Call {
	_c.Call.Return(run)
	return _c
}

// DeductExpenseBalance provides a mock function with given fields: ctx, tx, userID, amount
func (_m *BalanceRepository) DeductExpenseBalance(ctx context.Context, tx interfaces.Tx, userID int64, amount float64) error {
	ret := _m.Called(ctx, tx, userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for DeductExpenseBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64, float64) error); ok {
		r0 = rf(ctx, tx, userID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BalanceRepository_DeductExpenseBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeductExpenseBalance'
type BalanceRepository_DeductExpenseBalance_Call struct {
	*mock.Call
}

// DeductExpenseBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - userID int64
//   - amount float64
func (_e *BalanceRepository_Expecter) DeductExpenseBalance(ctx interface{}, tx interface{}, userID interface{}, amount interface{}) *BalanceRepository_DeductExpenseBalance_Call {
	return &BalanceRepository_DeductExpenseBalance_Call{Call: _e.mock.On("DeductExpenseBalance", ctx, tx, userID, amount)}
}

func (_c *BalanceRepository_DeductExpenseBalance_Call) Run(run func(ctx context.Context, tx interfaces.Tx, userID int64, amount float64)) *BalanceRepository_DeductExpenseBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64), args[3].(float64))
	})
	return _c
}

func (_c *BalanceRepository_DeductExpenseBalance_Call) Return(_a0 error) *BalanceRepository_DeductExpenseBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BalanceRepository_DeductExpenseBalance_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64, float64) error) *BalanceRepository_DeductExpenseBalance_Call {
	_c.Call.Return(run)
	return _c
}

// DeductLeaveBalance provides a mock function with given fields: ctx, tx, userID, days
func (_m *BalanceRepository) DeductLeaveBalance(ctx context.Context, tx interfaces.Tx, userID int64, days int) error {
	ret := _m.Called(ctx, tx, userID, days)

	if len(ret) == 0 {
		panic("no return value specified for DeductLeaveBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64, int) error); ok {
		r0 = rf(ctx, tx, userID, days)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BalanceRepository_DeductLeaveBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeductLeaveBalance'
type BalanceRepository_DeductLeaveBalance_Call struct {
	*mock.Call
}

// DeductLeaveBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - userID int64
//   - days int
func (_e *BalanceRepository_Expecter) DeductLeaveBalance(ctx interface{}, tx interface{}, userID interface{}, days interface{}) *BalanceRepository_DeductLeaveBalance_Call {
	return &BalanceRepository_DeductLeaveBalance_Call{Call: _e.mock.On("DeductLeaveBalance", ctx, tx, userID, days)}
}

func (_c *BalanceRepository_DeductLeaveBalance_Call) Run(run func(ctx context.Context, tx interfaces.Tx, userID int64, days int)) *BalanceRepository_DeductLeaveBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64), args[3].(int))
	})
	return _c
}

func (_c *BalanceRepository_DeductLeaveBalance_Call) Return(_a0 error) *BalanceRepository_DeductLeaveBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BalanceRepository_DeductLeaveBalance_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64, int) error) *BalanceRepository_DeductLeaveBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetDiscountBalance provides a mock function with given fields: ctx, tx, userID
func (_m *BalanceRepository) GetDiscountBalance(ctx context.Context, tx interfaces.Tx, userID int64) (float64, error) {
	ret := _m.Called(ctx, tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDiscountBalance")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) (float64, error)); ok {
		return rf(ctx, tx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) float64); ok {
		r0 = rf(ctx, tx, userID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.Tx, int64) error); ok {
		r1 = rf(ctx, tx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BalanceRepository_GetDiscountBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDiscountBalance'
type BalanceRepository_GetDiscountBalance_Call struct {
	*mock.Call
}

// GetDiscountBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - userID int64
func (_e *BalanceRepository_Expecter) GetDiscountBalance(ctx interface{}, tx interface{}, userID interface{}) *BalanceRepository_GetDiscountBalance_Call {
	return &BalanceRepository_GetDiscountBalance_Call{Call: _e.mock.On("GetDiscountBalance", ctx, tx, userID)}
}

func (_c *BalanceRepository_GetDiscountBalance_Call) Run(run func(ctx context.Context, tx interfaces.Tx, userID int64)) *BalanceRepository_GetDiscountBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64))
	})
	return _c
}

func (_c *BalanceRepository_GetDiscountBalance_Call) Return(_a0 float64, _a1 error) *BalanceRepository_GetDiscountBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BalanceRepository_GetDiscountBalance_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64) (float64, error)) *BalanceRepository_GetDiscountBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetDiscountFullBalance provides a mock function with given fields: ctx, tx, userID
func (_m *BalanceRepository) GetDiscountFullBalance(ctx context.Context, tx interfaces.Tx, userID int64) (float64, float64, error) {
	ret := _m.Called(ctx, tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDiscountFullBalance")
	}

	var r0 float64
	var r1 float64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) (float64, float64, error)); ok {
		return rf(ctx, tx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) float64); ok {
		r0 = rf(ctx, tx, userID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.Tx, int64) float64); ok {
		r1 = rf(ctx, tx, userID)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, interfaces.Tx, int64) error); ok {
		r2 = rf(ctx, tx, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// BalanceRepository_GetDiscountFullBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDiscountFullBalance'
type BalanceRepository_GetDiscountFullBalance_Call struct {
	*mock.Call
}

// GetDiscountFullBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - userID int64
func (_e *BalanceRepository_Expecter) GetDiscountFullBalance(ctx interface{}, tx interface{}, userID interface{}) *BalanceRepository_GetDiscountFullBalance_Call {
	return &BalanceRepository_GetDiscountFullBalance_Call{Call: _e.mock.On("GetDiscountFullBalance", ctx, tx, userID)}
}

func (_c *BalanceRepository_GetDiscountFullBalance_Call) Run(run func(ctx context.Context, tx interfaces.Tx, userID int64)) *BalanceRepository_GetDiscountFullBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64))
	})
	return _c
}

func (_c *BalanceRepository_GetDiscountFullBalance_Call) Return(total float64, remaining float64, err error) *BalanceRepository_GetDiscountFullBalance_Call {
	_c.Call.Return(total, remaining, err)
	return _c
}

func (_c *BalanceRepository_GetDiscountFullBalance_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64) (float64, float64, error)) *BalanceRepository_GetDiscountFullBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpenseBalance provides a mock function with given fields: ctx, tx, userID
func (_m *BalanceRepository) GetExpenseBalance(ctx context.Context, tx interfaces.Tx, userID int64) (float64, error) {
	ret := _m.Called(ctx, tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetExpenseBalance")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) (float64, error)); ok {
		return rf(ctx, tx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) float64); ok {
		r0 = rf(ctx, tx, userID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.Tx, int64) error); ok {
		r1 = rf(ctx, tx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BalanceRepository_GetExpenseBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpenseBalance'
type BalanceRepository_GetExpenseBalance_Call struct {
	*mock.Call
}

// GetExpenseBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - userID int64
func (_e *BalanceRepository_Expecter) GetExpenseBalance(ctx interface{}, tx interface{}, userID interface{}) *BalanceRepository_GetExpenseBalance_Call {
	return &BalanceRepository_GetExpenseBalance_Call{Call: _e.mock.On("GetExpenseBalance", ctx, tx, userID)}
}

func (_c *BalanceRepository_GetExpenseBalance_Call) Run(run func(ctx context.Context, tx interfaces.Tx, userID int64)) *BalanceRepository_GetExpenseBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64))
	})
	return _c
}

func (_c *BalanceRepository_GetExpenseBalance_Call) Return(_a0 float64, _a1 error) *BalanceRepository_GetExpenseBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BalanceRepository_GetExpenseBalance_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64) (float64, error)) *BalanceRepository_GetExpenseBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpenseFullBalance provides a mock function with given fields: ctx, tx, userID
func (_m *BalanceRepository) GetExpenseFullBalance(ctx context.Context, tx interfaces.Tx, userID int64) (float64, float64, error) {
	ret := _m.Called(ctx, tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetExpenseFullBalance")
	}

	var r0 float64
	var r1 float64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) (float64, float64, error)); ok {
		return rf(ctx, tx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) float64); ok {
		r0 = rf(ctx, tx, userID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.Tx, int64) float64); ok {
		r1 = rf(ctx, tx, userID)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, interfaces.Tx, int64) error); ok {
		r2 = rf(ctx, tx, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// BalanceRepository_GetExpenseFullBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpenseFullBalance'
type BalanceRepository_GetExpenseFullBalance_Call struct {
	*mock.Call
}

// GetExpenseFullBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - userID int64
func (_e *BalanceRepository_Expecter) GetExpenseFullBalance(ctx interface{}, tx interface{}, userID interface{}) *BalanceRepository_GetExpenseFullBalance_Call {
	return &BalanceRepository_GetExpenseFullBalance_Call{Call: _e.mock.On("GetExpenseFullBalance", ctx, tx, userID)}
}

func (_c *BalanceRepository_GetExpenseFullBalance_Call) Run(run func(ctx context.Context, tx interfaces.Tx, userID int64)) *BalanceRepository_GetExpenseFullBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64))
	})
	return _c
}

func (_c *BalanceRepository_GetExpenseFullBalance_Call) Return(total float64, remaining float64, err error) *BalanceRepository_GetExpenseFullBalance_Call {
	_c.Call.Return(total, remaining, err)
	return _c
}

func (_c *BalanceRepository_GetExpenseFullBalance_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64) (float64, float64, error)) *BalanceRepository_GetExpenseFullBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeaveBalance provides a mock function with given fields: ctx, tx, userID
func (_m *BalanceRepository) GetLeaveBalance(ctx context.Context, tx interfaces.Tx, userID int64) (int, error) {
	ret := _m.Called(ctx, tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaveBalance")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) (int, error)); ok {
		return rf(ctx, tx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) int); ok {
		r0 = rf(ctx, tx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.Tx, int64) error); ok {
		r1 = rf(ctx, tx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BalanceRepository_GetLeaveBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaveBalance'
type BalanceRepository_GetLeaveBalance_Call struct {
	*mock.Call
}

// GetLeaveBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - userID int64
func (_e *BalanceRepository_Expecter) GetLeaveBalance(ctx interface{}, tx interface{}, userID interface{}) *BalanceRepository_GetLeaveBalance_Call {
	return &BalanceRepository_GetLeaveBalance_Call{Call: _e.mock.On("GetLeaveBalance", ctx, tx, userID)}
}

func (_c *BalanceRepository_GetLeaveBalance_Call) Run(run func(ctx context.Context, tx interfaces.Tx, userID int64)) *BalanceRepository_GetLeaveBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64))
	})
	return _c
}

func (_c *BalanceRepository_GetLeaveBalance_Call) Return(_a0 int, _a1 error) *BalanceRepository_GetLeaveBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BalanceRepository_GetLeaveBalance_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64) (int, error)) *BalanceRepository_GetLeaveBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeaveFullBalance provides a mock function with given fields: ctx, tx, userID
func (_m *BalanceRepository) GetLeaveFullBalance(ctx context.Context, tx interfaces.Tx, userID int64) (int, int, error) {
	ret := _m.Called(ctx, tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaveFullBalance")
	}

	var r0 int
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) (int, int, error)); ok {
		return rf(ctx, tx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) int); ok {
		r0 = rf(ctx, tx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.Tx, int64) int); ok {
		r1 = rf(ctx, tx, userID)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, interfaces.Tx, int64) error); ok {
		r2 = rf(ctx, tx, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// BalanceRepository_GetLeaveFullBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaveFullBalance'
type BalanceRepository_GetLeaveFullBalance_Call struct {
	*mock.Call
}

// GetLeaveFullBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - userID int64
func (_e *BalanceRepository_Expecter) GetLeaveFullBalance(ctx interface{}, tx interface{}, userID interface{}) *BalanceRepository_GetLeaveFullBalance_Call {
	return &BalanceRepository_GetLeaveFullBalance_Call{Call: _e.mock.On("GetLeaveFullBalance", ctx, tx, userID)}
}

func (_c *BalanceRepository_GetLeaveFullBalance_Call) Run(run func(ctx context.Context, tx interfaces.Tx, userID int64)) *BalanceRepository_GetLeaveFullBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64))
	})
	return _c
}

func (_c *BalanceRepository_GetLeaveFullBalance_Call) Return(total int, remaining int, err error) *BalanceRepository_GetLeaveFullBalance_Call {
	_c.Call.Return(total, remaining, err)
	return _c
}

func (_c *BalanceRepository_GetLeaveFullBalance_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64) (int, int, error)) *BalanceRepository_GetLeaveFullBalance_Call {
	_c.Call.Return(run)
	return _c
}

// InitializeBalances provides a mock function with given fields: ctx, tx, userID, gradeID
func (_m *BalanceRepository) InitializeBalances(ctx context.Context, tx interfaces.Tx, userID int64, gradeID int64) error {
	ret := _m.Called(ctx, tx, userID, gradeID)

	if len(ret) == 0 {
		panic("no return value specified for InitializeBalances")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64, int64) error); ok {
		r0 = rf(ctx, tx, userID, gradeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BalanceRepository_InitializeBalances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitializeBalances'
type BalanceRepository_InitializeBalances_Call struct {
	*mock.Call
}

// InitializeBalances is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - userID int64
//   - gradeID int64
func (_e *BalanceRepository_Expecter) InitializeBalances(ctx interface{}, tx interface{}, userID interface{}, gradeID interface{}) *BalanceRepository_InitializeBalances_Call {
	return &BalanceRepository_InitializeBalances_Call{Call: _e.mock.On("InitializeBalances", ctx, tx, userID, gradeID)}
}

func (_c *BalanceRepository_InitializeBalances_Call) Run(run func(ctx context.Context, tx interfaces.Tx, userID int64, gradeID int64)) *BalanceRepository_InitializeBalances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64), args[3].(int64))
	})
	return _c
}

func (_c *BalanceRepository_InitializeBalances_Call) Return(_a0 error) *BalanceRepository_InitializeBalances_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BalanceRepository_InitializeBalances_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64, int64) error) *BalanceRepository_InitializeBalances_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreDiscountBalance provides a mock function with given fields: ctx, tx, userID, percent
func (_m *BalanceRepository) RestoreDiscountBalance(ctx context.Context, tx interfaces.Tx, userID int64, percent float64) error {
	ret := _m.Called(ctx, tx, userID, percent)

	if len(ret) == 0 {
		panic("no return value specified for RestoreDiscountBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64, float64) error); ok {
		r0 = rf(ctx, tx, userID, percent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BalanceRepository_RestoreDiscountBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreDiscountBalance'
type BalanceRepository_RestoreDiscountBalance_Call struct {
	*mock.Call
}

// RestoreDiscountBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - userID int64
//   - percent float64
func (_e *BalanceRepository_Expecter) RestoreDiscountBalance(ctx interface{}, tx interface{}, userID interface{}, percent interface{}) *BalanceRepository_RestoreDiscountBalance_Call {
	return &BalanceRepository_RestoreDiscountBalance_Call{Call: _e.mock.On("RestoreDiscountBalance", ctx, tx, userID, percent)}
}

func (_c *BalanceRepository_RestoreDiscountBalance_Call) Run(run func(ctx context.Context, tx interfaces.Tx, userID int64, percent float64)) *BalanceRepository_RestoreDiscountBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64), args[3].(float64))
	})
	return _c
}

func (_c *BalanceRepository_RestoreDiscountBalance_Call) Return(_a0 error) *BalanceRepository_RestoreDiscountBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BalanceRepository_RestoreDiscountBalance_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64, float64) error) *BalanceRepository_RestoreDiscountBalance_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreExpenseBalance provides a mock function with given fields: ctx, tx, userID, amount
func (_m *BalanceRepository) RestoreExpenseBalance(ctx context.Context, tx interfaces.Tx, userID int64, amount float64) error {
	ret := _m.Called(ctx, tx, userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for RestoreExpenseBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64, float64) error); ok {
		r0 = rf(ctx, tx, userID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BalanceRepository_RestoreExpenseBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreExpenseBalance'
type BalanceRepository_RestoreExpenseBalance_Call struct {
	*mock.Call
}

// RestoreExpenseBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - userID int64
//   - amount float64
func (_e *BalanceRepository_Expecter) RestoreExpenseBalance(ctx interface{}, tx interface{}, userID interface{}, amount interface{}) *BalanceRepository_RestoreExpenseBalance_Call {
	return &BalanceRepository_RestoreExpenseBalance_Call{Call: _e.mock.On("RestoreExpenseBalance", ctx, tx, userID, amount)}
}

func (_c *BalanceRepository_RestoreExpenseBalance_Call) Run(run func(ctx context.Context, tx interfaces.Tx, userID int64, amount float64)) *BalanceRepository_RestoreExpenseBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64), args[3].(float64))
	})
	return _c
}

func (_c *BalanceRepository_RestoreExpenseBalance_Call) Return(_a0 error) *BalanceRepository_RestoreExpenseBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BalanceRepository_RestoreExpenseBalance_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64, float64) error) *BalanceRepository_RestoreExpenseBalance_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreLeaveBalance provides a mock function with given fields: ctx, tx, userID, days
func (_m *BalanceRepository) RestoreLeaveBalance(ctx context.Context, tx interfaces.Tx, userID int64, days int) error {
	ret := _m.Called(ctx, tx, userID, days)

	if len(ret) == 0 {
		panic("no return value specified for RestoreLeaveBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64, int) error); ok {
		r0 = rf(ctx, tx, userID, days)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BalanceRepository_RestoreLeaveBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreLeaveBalance'
type BalanceRepository_RestoreLeaveBalance_Call struct {
	*mock.Call
}

// RestoreLeaveBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - userID int64
//   - days int
func (_e *BalanceRepository_Expecter) RestoreLeaveBalance(ctx interface{}, tx interface{}, userID interface{}, days interface{}) *BalanceRepository_RestoreLeaveBalance_Call {
	return &BalanceRepository_RestoreLeaveBalance_Call{Call: _e.mock.On("RestoreLeaveBalance", ctx, tx, userID, days)}
}

func (_c *BalanceRepository_RestoreLeaveBalance_Call) Run(run func(ctx context.Context, tx interfaces.Tx, userID int64, days int)) *BalanceRepository_RestoreLeaveBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64), args[3].(int))
	})
	return _c
}

func (_c *BalanceRepository_RestoreLeaveBalance_Call) Return(_a0 error) *BalanceRepository_RestoreLeaveBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BalanceRepository_RestoreLeaveBalance_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64, int) error) *BalanceRepository_RestoreLeaveBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewBalanceRepository creates a new instance of BalanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceRepository {
	mock := &BalanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
