package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DiscountServiceInterface is an autogenerated mock type for the DiscountServiceInterface type
type DiscountServiceInterface struct {
	mock.Mock
}

// ApplyDiscount provides a mock function with given fields: ctx, userID, percent, reason
func (_m *DiscountServiceInterface) ApplyDiscount(ctx context.Context, userID int64, percent float64, reason string) (string, string, error) {
	ret := _m.Called(ctx, userID, percent, reason)

	if len(ret) == 0 {
		panic("no return value specified for ApplyDiscount")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, float64, string) (string, string, error)); ok {
		return rf(ctx, userID, percent, reason)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, float64, string) string); ok {
		r0 = rf(ctx, userID, percent, reason)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, float64, string) string); ok {
		r1 = rf(ctx, userID, percent, reason)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, float64, string) error); ok {
		r2 = rf(ctx, userID, percent, reason)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ApproveDiscount provides a mock function with given fields: ctx, role, approverID, requestID, comment
func (_m *DiscountServiceInterface) ApproveDiscount(ctx context.Context, role string, approverID int64, requestID int64, comment string) error {
	ret := _m.Called(ctx, role, approverID, requestID, comment)

	if len(ret) == 0 {
		panic("no return value specified for ApproveDiscount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) error); ok {
		r0 = rf(ctx, role, approverID, requestID, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CancelDiscount provides a mock function with given fields: ctx, userID, requestID
func (_m *DiscountServiceInterface) CancelDiscount(ctx context.Context, userID int64, requestID int64) error {
	ret := _m.Called(ctx, userID, requestID)

	if len(ret) == 0 {
		panic("no return value specified for CancelDiscount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPendingDiscountRequests provides a mock function with given fields: ctx, role, approverID
func (_m *DiscountServiceInterface) GetPendingDiscountRequests(ctx context.Context, role string, approverID int64) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, role, approverID)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingDiscountRequests")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]map[string]interface{}, error)); ok {
		return rf(ctx, role, approverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []map[string]interface{}); ok {
		r0 = rf(ctx, role, approverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, role, approverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RejectDiscount provides a mock function with given fields: ctx, role, approverID, requestID, comment
func (_m *DiscountServiceInterface) RejectDiscount(ctx context.Context, role string, approverID int64, requestID int64, comment string) error {
	ret := _m.Called(ctx, role, approverID, requestID, comment)

	if len(ret) == 0 {
		panic("no return value specified for RejectDiscount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) error); ok {
		r0 = rf(ctx, role, approverID, requestID, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDiscountServiceInterface creates a new instance of DiscountServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiscountServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *DiscountServiceInterface {
	mock := &DiscountServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
