package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ExpenseServiceInterface is an autogenerated mock type for the ExpenseServiceInterface type
type ExpenseServiceInterface struct {
	mock.Mock
}

// ApplyExpense provides a mock function with given fields: ctx, userID, amount, category, reason
func (_m *ExpenseServiceInterface) ApplyExpense(ctx context.Context, userID int64, amount float64, category string, reason string) (string, string, error) {
	ret := _m.Called(ctx, userID, amount, category, reason)

	if len(ret) == 0 {
		panic("no return value specified for ApplyExpense")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, float64, string, string) (string, string, error)); ok {
		return rf(ctx, userID, amount, category, reason)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, float64, string, string) string); ok {
		r0 = rf(ctx, userID, amount, category, reason)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, float64, string, string) string); ok {
		r1 = rf(ctx, userID, amount, category, reason)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, float64, string, string) error); ok {
		r2 = rf(ctx, userID, amount, category, reason)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// CancelExpense provides a mock function with given fields: ctx, userID, requestID
func (_m *ExpenseServiceInterface) CancelExpense(ctx context.Context, userID int64, requestID int64) error {
	ret := _m.Called(ctx, userID, requestID)

	if len(ret) == 0 {
		panic("no return value specified for CancelExpense")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewExpenseServiceInterface creates a new instance of ExpenseServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpenseServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpenseServiceInterface {
	mock := &ExpenseServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
