package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ExpenseApprovalServiceInterface is an autogenerated mock type for the ExpenseApprovalServiceInterface type
type ExpenseApprovalServiceInterface struct {
	mock.Mock
}

// ApproveExpense provides a mock function with given fields: ctx, role, approverID, requestID, comment
func (_m *ExpenseApprovalServiceInterface) ApproveExpense(ctx context.Context, role string, approverID int64, requestID int64, comment string) error {
	ret := _m.Called(ctx, role, approverID, requestID, comment)

	if len(ret) == 0 {
		panic("no return value specified for ApproveExpense")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) error); ok {
		r0 = rf(ctx, role, approverID, requestID, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPendingExpenseRequests provides a mock function with given fields: ctx, role, approverID
func (_m *ExpenseApprovalServiceInterface) GetPendingExpenseRequests(ctx context.Context, role string, approverID int64) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, role, approverID)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingExpenseRequests")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]map[string]interface{}, error)); ok {
		return rf(ctx, role, approverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []map[string]interface{}); ok {
		r0 = rf(ctx, role, approverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, role, approverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RejectExpense provides a mock function with given fields: ctx, role, approverID, requestID, comment
func (_m *ExpenseApprovalServiceInterface) RejectExpense(ctx context.Context, role string, approverID int64, requestID int64, comment string) error {
	ret := _m.Called(ctx, role, approverID, requestID, comment)

	if len(ret) == 0 {
		panic("no return value specified for RejectExpense")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) error); ok {
		r0 = rf(ctx, role, approverID, requestID, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewExpenseApprovalServiceInterface creates a new instance of ExpenseApprovalServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpenseApprovalServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpenseApprovalServiceInterface {
	mock := &ExpenseApprovalServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
