// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// LeaveServiceInterface is an autogenerated mock type for the LeaveServiceInterface type
type LeaveServiceInterface struct {
	mock.Mock
}

// ApplyLeave provides a mock function with given fields: ctx, userID, from, to, days, leaveType, reason
func (_m *LeaveServiceInterface) ApplyLeave(ctx context.Context, userID int64, from time.Time, to time.Time, days int, leaveType string, reason string) (string, string, error) {
	ret := _m.Called(ctx, userID, from, to, days, leaveType, reason)

	if len(ret) == 0 {
		panic("no return value specified for ApplyLeave")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time, int, string, string) (string, string, error)); ok {
		return rf(ctx, userID, from, to, days, leaveType, reason)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time, int, string, string) string); ok {
		r0 = rf(ctx, userID, from, to, days, leaveType, reason)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, time.Time, time.Time, int, string, string) string); ok {
		r1 = rf(ctx, userID, from, to, days, leaveType, reason)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, time.Time, time.Time, int, string, string) error); ok {
		r2 = rf(ctx, userID, from, to, days, leaveType, reason)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// CancelLeave provides a mock function with given fields: ctx, userID, requestID
func (_m *LeaveServiceInterface) CancelLeave(ctx context.Context, userID int64, requestID int64) error {
	ret := _m.Called(ctx, userID, requestID)

	if len(ret) == 0 {
		panic("no return value specified for CancelLeave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLeaveServiceInterface creates a new instance of LeaveServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaveServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaveServiceInterface {
	mock := &LeaveServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
