package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// LeaveApprovalServiceInterface is an autogenerated mock type for the LeaveApprovalServiceInterface type
type LeaveApprovalServiceInterface struct {
	mock.Mock
}

// ApproveLeave provides a mock function with given fields: ctx, role, approverID, requestID, approvalComment
func (_m *LeaveApprovalServiceInterface) ApproveLeave(ctx context.Context, role string, approverID int64, requestID int64, approvalComment string) error {
	ret := _m.Called(ctx, role, approverID, requestID, approvalComment)

	if len(ret) == 0 {
		panic("no return value specified for ApproveLeave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) error); ok {
		r0 = rf(ctx, role, approverID, requestID, approvalComment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPendingLeaveRequests provides a mock function with given fields: ctx, role, approverID
func (_m *LeaveApprovalServiceInterface) GetPendingLeaveRequests(ctx context.Context, role string, approverID int64) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, role, approverID)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingLeaveRequests")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) ([]map[string]interface{}, error)); ok {
		return rf(ctx, role, approverID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) []map[string]interface{}); ok {
		r0 = rf(ctx, role, approverID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, role, approverID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RejectLeave provides a mock function with given fields: ctx, role, approverID, requestID, rejectionComment
func (_m *LeaveApprovalServiceInterface) RejectLeave(ctx context.Context, role string, approverID int64, requestID int64, rejectionComment string) error {
	ret := _m.Called(ctx, role, approverID, requestID, rejectionComment)

	if len(ret) == 0 {
		panic("no return value specified for RejectLeave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, string) error); ok {
		r0 = rf(ctx, role, approverID, requestID, rejectionComment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLeaveApprovalServiceInterface creates a new instance of LeaveApprovalServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaveApprovalServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaveApprovalServiceInterface {
	mock := &LeaveApprovalServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
