// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// LeaveService is an autogenerated mock type for the LeaveService type
type LeaveService struct {
	mock.Mock
}

type LeaveService_Expecter struct {
	mock *mock.Mock
}

func (_m *LeaveService) EXPECT() *LeaveService_Expecter {
	return &LeaveService_Expecter{mock: &_m.Mock}
}

// ApplyLeave provides a mock function with given fields: ctx, userID, from, to, days, leaveType, reason
func (_m *LeaveService) ApplyLeave(ctx context.Context, userID int64, from time.Time, to time.Time, days int, leaveType string, reason string) (string, string, error) {
	ret := _m.Called(ctx, userID, from, to, days, leaveType, reason)

	if len(ret) == 0 {
		panic("no return value specified for ApplyLeave")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time, int, string, string) (string, string, error)); ok {
		return rf(ctx, userID, from, to, days, leaveType, reason)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time, int, string, string) string); ok {
		r0 = rf(ctx, userID, from, to, days, leaveType, reason)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, time.Time, time.Time, int, string, string) string); ok {
		r1 = rf(ctx, userID, from, to, days, leaveType, reason)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int64, time.Time, time.Time, int, string, string) error); ok {
		r2 = rf(ctx, userID, from, to, days, leaveType, reason)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// LeaveService_ApplyLeave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyLeave'
type LeaveService_ApplyLeave_Call struct {
	*mock.Call
}

// ApplyLeave is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - from time.Time
//   - to time.Time
//   - days int
//   - leaveType string
//   - reason string
func (_e *LeaveService_Expecter) ApplyLeave(ctx interface{}, userID interface{}, from interface{}, to interface{}, days interface{}, leaveType interface{}, reason interface{}) *LeaveService_ApplyLeave_Call {
	return &LeaveService_ApplyLeave_Call{Call: _e.mock.On("ApplyLeave", ctx, userID, from, to, days, leaveType, reason)}
}

func (_c *LeaveService_ApplyLeave_Call) Run(run func(ctx context.Context, userID int64, from time.Time, to time.Time, days int, leaveType string, reason string)) *LeaveService_ApplyLeave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(time.Time), args[3].(time.Time), args[4].(int), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *LeaveService_ApplyLeave_Call) Return(_a0 string, _a1 string, _a2 error) *LeaveService_ApplyLeave_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *LeaveService_ApplyLeave_Call) RunAndReturn(run func(context.Context, int64, time.Time, time.Time, int, string, string) (string, string, error)) *LeaveService_ApplyLeave_Call {
	_c.Call.Return(run)
	return _c
}

// CancelLeave provides a mock function with given fields: ctx, userID, requestID
func (_m *LeaveService) CancelLeave(ctx context.Context, userID int64, requestID int64) error {
	ret := _m.Called(ctx, userID, requestID)

	if len(ret) == 0 {
		panic("no return value specified for CancelLeave")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LeaveService_CancelLeave_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelLeave'
type LeaveService_CancelLeave_Call struct {
	*mock.Call
}

// CancelLeave is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - requestID int64
func (_e *LeaveService_Expecter) CancelLeave(ctx interface{}, userID interface{}, requestID interface{}) *LeaveService_CancelLeave_Call {
	return &LeaveService_CancelLeave_Call{Call: _e.mock.On("CancelLeave", ctx, userID, requestID)}
}

func (_c *LeaveService_CancelLeave_Call) Run(run func(ctx context.Context, userID int64, requestID int64)) *LeaveService_CancelLeave_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *LeaveService_CancelLeave_Call) Return(_a0 error) *LeaveService_CancelLeave_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LeaveService_CancelLeave_Call) RunAndReturn(run func(context.Context, int64, int64) error) *LeaveService_CancelLeave_Call {
	_c.Call.Return(run)
	return _c
}

// NewLeaveService creates a new instance of LeaveService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaveService(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaveService {
	mock := &LeaveService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
