// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/ankita-advitot/rule_based_approval_engine/models"
)

// RuleService is an autogenerated mock type for the RuleService type
type RuleService struct {
	mock.Mock
}

type RuleService_Expecter struct {
	mock *mock.Mock
}

func (_m *RuleService) EXPECT() *RuleService_Expecter {
	return &RuleService_Expecter{mock: &_m.Mock}
}

// CreateRule provides a mock function with given fields: ctx, role, rule
func (_m *RuleService) CreateRule(ctx context.Context, role string, rule models.Rule) error {
	ret := _m.Called(ctx, role, rule)

	if len(ret) == 0 {
		panic("no return value specified for CreateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.Rule) error); ok {
		r0 = rf(ctx, role, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RuleService_CreateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRule'
type RuleService_CreateRule_Call struct {
	*mock.Call
}

// CreateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - rule models.Rule
func (_e *RuleService_Expecter) CreateRule(ctx interface{}, role interface{}, rule interface{}) *RuleService_CreateRule_Call {
	return &RuleService_CreateRule_Call{Call: _e.mock.On("CreateRule", ctx, role, rule)}
}

func (_c *RuleService_CreateRule_Call) Run(run func(ctx context.Context, role string, rule models.Rule)) *RuleService_CreateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.Rule))
	})
	return _c
}

func (_c *RuleService_CreateRule_Call) Return(_a0 error) *RuleService_CreateRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RuleService_CreateRule_Call) RunAndReturn(run func(context.Context, string, models.Rule) error) *RuleService_CreateRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRule provides a mock function with given fields: ctx, role, ruleID
func (_m *RuleService) DeleteRule(ctx context.Context, role string, ruleID int64) error {
	ret := _m.Called(ctx, role, ruleID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, role, ruleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RuleService_DeleteRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRule'
type RuleService_DeleteRule_Call struct {
	*mock.Call
}

// DeleteRule is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - ruleID int64
func (_e *RuleService_Expecter) DeleteRule(ctx interface{}, role interface{}, ruleID interface{}) *RuleService_DeleteRule_Call {
	return &RuleService_DeleteRule_Call{Call: _e.mock.On("DeleteRule", ctx, role, ruleID)}
}

func (_c *RuleService_DeleteRule_Call) Run(run func(ctx context.Context, role string, ruleID int64)) *RuleService_DeleteRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *RuleService_DeleteRule_Call) Return(_a0 error) *RuleService_DeleteRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RuleService_DeleteRule_Call) RunAndReturn(run func(context.Context, string, int64) error) *RuleService_DeleteRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetRule provides a mock function with given fields: ctx, requestType, gradeID
func (_m *RuleService) GetRule(ctx context.Context, requestType string, gradeID int64) (*models.Rule, error) {
	ret := _m.Called(ctx, requestType, gradeID)

	if len(ret) == 0 {
		panic("no return value specified for GetRule")
	}

	var r0 *models.Rule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (*models.Rule, error)); ok {
		return rf(ctx, requestType, gradeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) *models.Rule); ok {
		r0 = rf(ctx, requestType, gradeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Rule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, requestType, gradeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RuleService_GetRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRule'
type RuleService_GetRule_Call struct {
	*mock.Call
}

// GetRule is a helper method to define mock.On call
//   - ctx context.Context
//   - requestType string
//   - gradeID int64
func (_e *RuleService_Expecter) GetRule(ctx interface{}, requestType interface{}, gradeID interface{}) *RuleService_GetRule_Call {
	return &RuleService_GetRule_Call{Call: _e.mock.On("GetRule", ctx, requestType, gradeID)}
}

func (_c *RuleService_GetRule_Call) Run(run func(ctx context.Context, requestType string, gradeID int64)) *RuleService_GetRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *RuleService_GetRule_Call) Return(_a0 *models.Rule, _a1 error) *RuleService_GetRule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RuleService_GetRule_Call) RunAndReturn(run func(context.Context, string, int64) (*models.Rule, error)) *RuleService_GetRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetRules provides a mock function with given fields: ctx, role
func (_m *RuleService) GetRules(ctx context.Context, role string) ([]models.Rule, error) {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for GetRules")
	}

	var r0 []models.Rule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Rule, error)); ok {
		return rf(ctx, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Rule); ok {
		r0 = rf(ctx, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Rule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RuleService_GetRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRules'
type RuleService_GetRules_Call struct {
	*mock.Call
}

// GetRules is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
func (_e *RuleService_Expecter) GetRules(ctx interface{}, role interface{}) *RuleService_GetRules_Call {
	return &RuleService_GetRules_Call{Call: _e.mock.On("GetRules", ctx, role)}
}

func (_c *RuleService_GetRules_Call) Run(run func(ctx context.Context, role string)) *RuleService_GetRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RuleService_GetRules_Call) Return(_a0 []models.Rule, _a1 error) *RuleService_GetRules_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RuleService_GetRules_Call) RunAndReturn(run func(context.Context, string) ([]models.Rule, error)) *RuleService_GetRules_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRule provides a mock function with given fields: ctx, role, ruleID, rule
func (_m *RuleService) UpdateRule(ctx context.Context, role string, ruleID int64, rule models.Rule) error {
	ret := _m.Called(ctx, role, ruleID, rule)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, models.Rule) error); ok {
		r0 = rf(ctx, role, ruleID, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RuleService_UpdateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRule'
type RuleService_UpdateRule_Call struct {
	*mock.Call
}

// UpdateRule is a helper method to define mock.On call
//   - ctx context.Context
//   - role string
//   - ruleID int64
//   - rule models.Rule
func (_e *RuleService_Expecter) UpdateRule(ctx interface{}, role interface{}, ruleID interface{}, rule interface{}) *RuleService_UpdateRule_Call {
	return &RuleService_UpdateRule_Call{Call: _e.mock.On("UpdateRule", ctx, role, ruleID, rule)}
}

func (_c *RuleService_UpdateRule_Call) Run(run func(ctx context.Context, role string, ruleID int64, rule models.Rule)) *RuleService_UpdateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64), args[3].(models.Rule))
	})
	return _c
}

func (_c *RuleService_UpdateRule_Call) Return(_a0 error) *RuleService_UpdateRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RuleService_UpdateRule_Call) RunAndReturn(run func(context.Context, string, int64, models.Rule) error) *RuleService_UpdateRule_Call {
	_c.Call.Return(run)
	return _c
}

// NewRuleService creates a new instance of RuleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRuleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RuleService {
	mock := &RuleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
