// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/ankita-advitot/rule_based_approval_engine/models"
)

// RuleRepository is an autogenerated mock type for the RuleRepository type
type RuleRepository struct {
	mock.Mock
}

type RuleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RuleRepository) EXPECT() *RuleRepository_Expecter {
	return &RuleRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, rule
func (_m *RuleRepository) Create(ctx context.Context, rule *models.Rule) error {
	ret := _m.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Rule) error); ok {
		r0 = rf(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RuleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RuleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - rule *models.Rule
func (_e *RuleRepository_Expecter) Create(ctx interface{}, rule interface{}) *RuleRepository_Create_Call {
	return &RuleRepository_Create_Call{Call: _e.mock.On("Create", ctx, rule)}
}

func (_c *RuleRepository_Create_Call) Run(run func(ctx context.Context, rule *models.Rule)) *RuleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Rule))
	})
	return _c
}

func (_c *RuleRepository_Create_Call) Return(_a0 error) *RuleRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RuleRepository_Create_Call) RunAndReturn(run func(context.Context, *models.Rule) error) *RuleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, ruleID
func (_m *RuleRepository) Delete(ctx context.Context, ruleID int64) error {
	ret := _m.Called(ctx, ruleID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, ruleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RuleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RuleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - ruleID int64
func (_e *RuleRepository_Expecter) Delete(ctx interface{}, ruleID interface{}) *RuleRepository_Delete_Call {
	return &RuleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, ruleID)}
}

func (_c *RuleRepository_Delete_Call) Run(run func(ctx context.Context, ruleID int64)) *RuleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *RuleRepository_Delete_Call) Return(_a0 error) *RuleRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RuleRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *RuleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *RuleRepository) GetAll(ctx context.Context) ([]models.Rule, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Rule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Rule, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Rule); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Rule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RuleRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type RuleRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RuleRepository_Expecter) GetAll(ctx interface{}) *RuleRepository_GetAll_Call {
	return &RuleRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *RuleRepository_GetAll_Call) Run(run func(ctx context.Context)) *RuleRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RuleRepository_GetAll_Call) Return(_a0 []models.Rule, _a1 error) *RuleRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RuleRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]models.Rule, error)) *RuleRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTypeAndGrade provides a mock function with given fields: ctx, requestType, gradeID
func (_m *RuleRepository) GetByTypeAndGrade(ctx context.Context, requestType string, gradeID int64) (*models.Rule, error) {
	ret := _m.Called(ctx, requestType, gradeID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTypeAndGrade")
	}

	var r0 *models.Rule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (*models.Rule, error)); ok {
		return rf(ctx, requestType, gradeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) *models.Rule); ok {
		r0 = rf(ctx, requestType, gradeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Rule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, requestType, gradeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RuleRepository_GetByTypeAndGrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTypeAndGrade'
type RuleRepository_GetByTypeAndGrade_Call struct {
	*mock.Call
}

// GetByTypeAndGrade is a helper method to define mock.On call
//   - ctx context.Context
//   - requestType string
//   - gradeID int64
func (_e *RuleRepository_Expecter) GetByTypeAndGrade(ctx interface{}, requestType interface{}, gradeID interface{}) *RuleRepository_GetByTypeAndGrade_Call {
	return &RuleRepository_GetByTypeAndGrade_Call{Call: _e.mock.On("GetByTypeAndGrade", ctx, requestType, gradeID)}
}

func (_c *RuleRepository_GetByTypeAndGrade_Call) Run(run func(ctx context.Context, requestType string, gradeID int64)) *RuleRepository_GetByTypeAndGrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *RuleRepository_GetByTypeAndGrade_Call) Return(_a0 *models.Rule, _a1 error) *RuleRepository_GetByTypeAndGrade_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RuleRepository_GetByTypeAndGrade_Call) RunAndReturn(run func(context.Context, string, int64) (*models.Rule, error)) *RuleRepository_GetByTypeAndGrade_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, ruleID, rule
func (_m *RuleRepository) Update(ctx context.Context, ruleID int64, rule *models.Rule) error {
	ret := _m.Called(ctx, ruleID, rule)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *models.Rule) error); ok {
		r0 = rf(ctx, ruleID, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RuleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RuleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ruleID int64
//   - rule *models.Rule
func (_e *RuleRepository_Expecter) Update(ctx interface{}, ruleID interface{}, rule interface{}) *RuleRepository_Update_Call {
	return &RuleRepository_Update_Call{Call: _e.mock.On("Update", ctx, ruleID, rule)}
}

func (_c *RuleRepository_Update_Call) Run(run func(ctx context.Context, ruleID int64, rule *models.Rule)) *RuleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*models.Rule))
	})
	return _c
}

func (_c *RuleRepository_Update_Call) Return(_a0 error) *RuleRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RuleRepository_Update_Call) RunAndReturn(run func(context.Context, int64, *models.Rule) error) *RuleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRuleRepository creates a new instance of RuleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRuleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RuleRepository {
	mock := &RuleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
