// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// BalanceRepository is an autogenerated mock type for the BalanceRepository type
type BalanceRepository struct {
	mock.Mock
}

// DeductExpenseBalance provides a mock function with given fields: ctx, tx, userID, amount
func (_m *BalanceRepository) DeductExpenseBalance(ctx context.Context, tx pgx.Tx, userID int64, amount float64) error {
	ret := _m.Called(ctx, tx, userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for DeductExpenseBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64, float64) error); ok {
		r0 = rf(ctx, tx, userID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeductLeaveBalance provides a mock function with given fields: ctx, tx, userID, days
func (_m *BalanceRepository) DeductLeaveBalance(ctx context.Context, tx pgx.Tx, userID int64, days int) error {
	ret := _m.Called(ctx, tx, userID, days)

	if len(ret) == 0 {
		panic("no return value specified for DeductLeaveBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64, int) error); ok {
		r0 = rf(ctx, tx, userID, days)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetExpenseBalance provides a mock function with given fields: ctx, tx, userID
func (_m *BalanceRepository) GetExpenseBalance(ctx context.Context, tx pgx.Tx, userID int64) (float64, error) {
	ret := _m.Called(ctx, tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetExpenseBalance")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) (float64, error)); ok {
		return rf(ctx, tx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) float64); ok {
		r0 = rf(ctx, tx, userID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, int64) error); ok {
		r1 = rf(ctx, tx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLeaveBalance provides a mock function with given fields: ctx, tx, userID
func (_m *BalanceRepository) GetLeaveBalance(ctx context.Context, tx pgx.Tx, userID int64) (int, error) {
	ret := _m.Called(ctx, tx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaveBalance")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) (int, error)); ok {
		return rf(ctx, tx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) int); ok {
		r0 = rf(ctx, tx, userID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, int64) error); ok {
		r1 = rf(ctx, tx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitializeBalances provides a mock function with given fields: ctx, tx, userID, gradeID
func (_m *BalanceRepository) InitializeBalances(ctx context.Context, tx pgx.Tx, userID int64, gradeID int64) error {
	ret := _m.Called(ctx, tx, userID, gradeID)

	if len(ret) == 0 {
		panic("no return value specified for InitializeBalances")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64, int64) error); ok {
		r0 = rf(ctx, tx, userID, gradeID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RestoreExpenseBalance provides a mock function with given fields: ctx, tx, userID, amount
func (_m *BalanceRepository) RestoreExpenseBalance(ctx context.Context, tx pgx.Tx, userID int64, amount float64) error {
	ret := _m.Called(ctx, tx, userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for RestoreExpenseBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64, float64) error); ok {
		r0 = rf(ctx, tx, userID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RestoreLeaveBalance provides a mock function with given fields: ctx, tx, userID, days
func (_m *BalanceRepository) RestoreLeaveBalance(ctx context.Context, tx pgx.Tx, userID int64, days int) error {
	ret := _m.Called(ctx, tx, userID, days)

	if len(ret) == 0 {
		panic("no return value specified for RestoreLeaveBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64, int) error); ok {
		r0 = rf(ctx, tx, userID, days)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBalanceRepository creates a new instance of BalanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceRepository {
	mock := &BalanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
