// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "rule-based-approval-engine/internal/models"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	time "time"
)

// autogenerated mock type for the DiscountRequestRepository type
type DiscountRequestRepository struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: ctx, tx, requestID
func (_m *DiscountRequestRepository) Cancel(ctx context.Context, tx pgx.Tx, requestID int64) error {
	ret := _m.Called(ctx, tx, requestID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) error); ok {
		r0 = rf(ctx, tx, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, tx, req
func (_m *DiscountRequestRepository) Create(ctx context.Context, tx pgx.Tx, req *models.DiscountRequest) error {
	ret := _m.Called(ctx, tx, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, *models.DiscountRequest) error); ok {
		r0 = rf(ctx, tx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, tx, requestID
func (_m *DiscountRequestRepository) GetByID(ctx context.Context, tx pgx.Tx, requestID int64) (*models.DiscountRequest, error) {
	ret := _m.Called(ctx, tx, requestID)

	var r0 *models.DiscountRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) (*models.DiscountRequest, error)); ok {
		return rf(ctx, tx, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) *models.DiscountRequest); ok {
		r0 = rf(ctx, tx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DiscountRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, int64) error); ok {
		r1 = rf(ctx, tx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingForAdmin provides a mock function with given fields: ctx
func (_m *DiscountRequestRepository) GetPendingForAdmin(ctx context.Context) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx)

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]map[string]interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingForManager provides a mock function with given fields: ctx, managerID
func (_m *DiscountRequestRepository) GetPendingForManager(ctx context.Context, managerID int64) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, managerID)

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]map[string]interface{}, error)); ok {
		return rf(ctx, managerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []map[string]interface{}); ok {
		r0 = rf(ctx, managerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, managerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, tx, requestID, status, approverID, comment
func (_m *DiscountRequestRepository) UpdateStatus(ctx context.Context, tx pgx.Tx, requestID int64, status string, approverID int64, comment string) error {
	ret := _m.Called(ctx, tx, requestID, status, approverID, comment)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64, string, int64, string) error); ok {
		r0 = rf(ctx, tx, requestID, status, approverID, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPendingRequests provides a mock function with given fields: ctx
func (_m *DiscountRequestRepository) GetPendingRequests(ctx context.Context) ([]struct {
	ID        int64
	CreatedAt time.Time
}, error) {
	ret := _m.Called(ctx)

	var r0 []struct {
		ID        int64
		CreatedAt time.Time
	}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]struct {
		ID        int64
		CreatedAt time.Time
	}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []struct {
		ID        int64
		CreatedAt time.Time
	}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]struct {
				ID        int64
				CreatedAt time.Time
			})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDiscountRequestRepository creates a new instance of DiscountRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDiscountRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DiscountRequestRepository {
	mock := &DiscountRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
