// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "rule-based-approval-engine/internal/models"

	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"

	time "time"
)

// LeaveRequestRepository is an autogenerated mock type for the LeaveRequestRepository type
type LeaveRequestRepository struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: ctx, tx, requestID
func (_m *LeaveRequestRepository) Cancel(ctx context.Context, tx pgx.Tx, requestID int64) error {
	ret := _m.Called(ctx, tx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) error); ok {
		r0 = rf(ctx, tx, requestID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckOverlap provides a mock function with given fields: ctx, userID, fromDate, toDate
func (_m *LeaveRequestRepository) CheckOverlap(ctx context.Context, userID int64, fromDate time.Time, toDate time.Time) (bool, error) {
	ret := _m.Called(ctx, userID, fromDate, toDate)

	if len(ret) == 0 {
		panic("no return value specified for CheckOverlap")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) (bool, error)); ok {
		return rf(ctx, userID, fromDate, toDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, time.Time, time.Time) bool); ok {
		r0 = rf(ctx, userID, fromDate, toDate)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, fromDate, toDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, tx, req
func (_m *LeaveRequestRepository) Create(ctx context.Context, tx pgx.Tx, req *models.LeaveRequest) error {
	ret := _m.Called(ctx, tx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, *models.LeaveRequest) error); ok {
		r0 = rf(ctx, tx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, tx, requestID
func (_m *LeaveRequestRepository) GetByID(ctx context.Context, tx pgx.Tx, requestID int64) (*models.LeaveRequest, error) {
	ret := _m.Called(ctx, tx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.LeaveRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) (*models.LeaveRequest, error)); ok {
		return rf(ctx, tx, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64) *models.LeaveRequest); ok {
		r0 = rf(ctx, tx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.LeaveRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgx.Tx, int64) error); ok {
		r1 = rf(ctx, tx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingForAdmin provides a mock function with given fields: ctx
func (_m *LeaveRequestRepository) GetPendingForAdmin(ctx context.Context) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingForAdmin")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]map[string]interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPendingForManager provides a mock function with given fields: ctx, managerID
func (_m *LeaveRequestRepository) GetPendingForManager(ctx context.Context, managerID int64) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, managerID)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingForManager")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]map[string]interface{}, error)); ok {
		return rf(ctx, managerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []map[string]interface{}); ok {
		r0 = rf(ctx, managerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, managerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, tx, requestID, status, approverID, comment
func (_m *LeaveRequestRepository) UpdateStatus(ctx context.Context, tx pgx.Tx, requestID int64, status string, approverID int64, comment string) error {
	ret := _m.Called(ctx, tx, requestID, status, approverID, comment)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgx.Tx, int64, string, int64, string) error); ok {
		r0 = rf(ctx, tx, requestID, status, approverID, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLeaveRequestRepository creates a new instance of LeaveRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLeaveRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LeaveRequestRepository {
	mock := &LeaveRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
