// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	models "rule-based-approval-engine/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// RuleRepository is an autogenerated mock type for the RuleRepository type
type RuleRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, rule
func (_m *RuleRepository) Create(ctx context.Context, rule *models.Rule) error {
	ret := _m.Called(ctx, rule)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Rule) error); ok {
		r0 = rf(ctx, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, ruleID
func (_m *RuleRepository) Delete(ctx context.Context, ruleID int64) error {
	ret := _m.Called(ctx, ruleID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, ruleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *RuleRepository) GetAll(ctx context.Context) ([]models.Rule, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Rule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Rule, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Rule); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Rule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTypeAndGrade provides a mock function with given fields: ctx, requestType, gradeID
func (_m *RuleRepository) GetByTypeAndGrade(ctx context.Context, requestType string, gradeID int64) (*models.Rule, error) {
	ret := _m.Called(ctx, requestType, gradeID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTypeAndGrade")
	}

	var r0 *models.Rule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) (*models.Rule, error)); ok {
		return rf(ctx, requestType, gradeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) *models.Rule); ok {
		r0 = rf(ctx, requestType, gradeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Rule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, requestType, gradeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, ruleID, rule
func (_m *RuleRepository) Update(ctx context.Context, ruleID int64, rule *models.Rule) error {
	ret := _m.Called(ctx, ruleID, rule)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *models.Rule) error); ok {
		r0 = rf(ctx, ruleID, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRuleRepository creates a new instance of RuleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRuleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RuleRepository {
	mock := &RuleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
