// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AutoRejectService is an autogenerated mock type for the AutoRejectService type
type AutoRejectService struct {
	mock.Mock
}

type AutoRejectService_Expecter struct {
	mock *mock.Mock
}

func (_m *AutoRejectService) EXPECT() *AutoRejectService_Expecter {
	return &AutoRejectService_Expecter{mock: &_m.Mock}
}

// AutoRejectExpiredRequests provides a mock function with given fields: ctx
func (_m *AutoRejectService) AutoRejectExpiredRequests(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AutoRejectExpiredRequests")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AutoRejectService_AutoRejectExpiredRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AutoRejectExpiredRequests'
type AutoRejectService_AutoRejectExpiredRequests_Call struct {
	*mock.Call
}

// AutoRejectExpiredRequests is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AutoRejectService_Expecter) AutoRejectExpiredRequests(ctx interface{}) *AutoRejectService_AutoRejectExpiredRequests_Call {
	return &AutoRejectService_AutoRejectExpiredRequests_Call{Call: _e.mock.On("AutoRejectExpiredRequests", ctx)}
}

func (_c *AutoRejectService_AutoRejectExpiredRequests_Call) Run(run func(ctx context.Context)) *AutoRejectService_AutoRejectExpiredRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AutoRejectService_AutoRejectExpiredRequests_Call) Return(_a0 error) *AutoRejectService_AutoRejectExpiredRequests_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AutoRejectService_AutoRejectExpiredRequests_Call) RunAndReturn(run func(context.Context) error) *AutoRejectService_AutoRejectExpiredRequests_Call {
	_c.Call.Return(run)
	return _c
}

// NewAutoRejectService creates a new instance of AutoRejectService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAutoRejectService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AutoRejectService {
	mock := &AutoRejectService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
