// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	interfaces "github.com/ankita-advitot/rule_based_approval_engine/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// GradeRepository is an autogenerated mock type for the GradeRepository type
type GradeRepository struct {
	mock.Mock
}

type GradeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *GradeRepository) EXPECT() *GradeRepository_Expecter {
	return &GradeRepository_Expecter{mock: &_m.Mock}
}

// GetLimits provides a mock function with given fields: ctx, tx, gradeID
func (_m *GradeRepository) GetLimits(ctx context.Context, tx interfaces.Tx, gradeID int64) (int, float64, float64, error) {
	ret := _m.Called(ctx, tx, gradeID)

	if len(ret) == 0 {
		panic("no return value specified for GetLimits")
	}

	var r0 int
	var r1 float64
	var r2 float64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) (int, float64, float64, error)); ok {
		return rf(ctx, tx, gradeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interfaces.Tx, int64) int); ok {
		r0 = rf(ctx, tx, gradeID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, interfaces.Tx, int64) float64); ok {
		r1 = rf(ctx, tx, gradeID)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, interfaces.Tx, int64) float64); ok {
		r2 = rf(ctx, tx, gradeID)
	} else {
		r2 = ret.Get(2).(float64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, interfaces.Tx, int64) error); ok {
		r3 = rf(ctx, tx, gradeID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GradeRepository_GetLimits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLimits'
type GradeRepository_GetLimits_Call struct {
	*mock.Call
}

// GetLimits is a helper method to define mock.On call
//   - ctx context.Context
//   - tx interfaces.Tx
//   - gradeID int64
func (_e *GradeRepository_Expecter) GetLimits(ctx interface{}, tx interface{}, gradeID interface{}) *GradeRepository_GetLimits_Call {
	return &GradeRepository_GetLimits_Call{Call: _e.mock.On("GetLimits", ctx, tx, gradeID)}
}

func (_c *GradeRepository_GetLimits_Call) Run(run func(ctx context.Context, tx interfaces.Tx, gradeID int64)) *GradeRepository_GetLimits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interfaces.Tx), args[2].(int64))
	})
	return _c
}

func (_c *GradeRepository_GetLimits_Call) Return(leaveLimit int, expenseLimit float64, discountLimit float64, err error) *GradeRepository_GetLimits_Call {
	_c.Call.Return(leaveLimit, expenseLimit, discountLimit, err)
	return _c
}

func (_c *GradeRepository_GetLimits_Call) RunAndReturn(run func(context.Context, interfaces.Tx, int64) (int, float64, float64, error)) *GradeRepository_GetLimits_Call {
	_c.Call.Return(run)
	return _c
}

// NewGradeRepository creates a new instance of GradeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGradeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GradeRepository {
	mock := &GradeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
