// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// HolidayRepository is an autogenerated mock type for the HolidayRepository type
type HolidayRepository struct {
	mock.Mock
}

type HolidayRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *HolidayRepository) EXPECT() *HolidayRepository_Expecter {
	return &HolidayRepository_Expecter{mock: &_m.Mock}
}

// AddHoliday provides a mock function with given fields: ctx, date, desc, adminID
func (_m *HolidayRepository) AddHoliday(ctx context.Context, date time.Time, desc string, adminID int64) error {
	ret := _m.Called(ctx, date, desc, adminID)

	if len(ret) == 0 {
		panic("no return value specified for AddHoliday")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, string, int64) error); ok {
		r0 = rf(ctx, date, desc, adminID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HolidayRepository_AddHoliday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddHoliday'
type HolidayRepository_AddHoliday_Call struct {
	*mock.Call
}

// AddHoliday is a helper method to define mock.On call
//   - ctx context.Context
//   - date time.Time
//   - desc string
//   - adminID int64
func (_e *HolidayRepository_Expecter) AddHoliday(ctx interface{}, date interface{}, desc interface{}, adminID interface{}) *HolidayRepository_AddHoliday_Call {
	return &HolidayRepository_AddHoliday_Call{Call: _e.mock.On("AddHoliday", ctx, date, desc, adminID)}
}

func (_c *HolidayRepository_AddHoliday_Call) Run(run func(ctx context.Context, date time.Time, desc string, adminID int64)) *HolidayRepository_AddHoliday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *HolidayRepository_AddHoliday_Call) Return(_a0 error) *HolidayRepository_AddHoliday_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HolidayRepository_AddHoliday_Call) RunAndReturn(run func(context.Context, time.Time, string, int64) error) *HolidayRepository_AddHoliday_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteHoliday provides a mock function with given fields: ctx, holidayID
func (_m *HolidayRepository) DeleteHoliday(ctx context.Context, holidayID int64) error {
	ret := _m.Called(ctx, holidayID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteHoliday")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, holidayID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HolidayRepository_DeleteHoliday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteHoliday'
type HolidayRepository_DeleteHoliday_Call struct {
	*mock.Call
}

// DeleteHoliday is a helper method to define mock.On call
//   - ctx context.Context
//   - holidayID int64
func (_e *HolidayRepository_Expecter) DeleteHoliday(ctx interface{}, holidayID interface{}) *HolidayRepository_DeleteHoliday_Call {
	return &HolidayRepository_DeleteHoliday_Call{Call: _e.mock.On("DeleteHoliday", ctx, holidayID)}
}

func (_c *HolidayRepository_DeleteHoliday_Call) Run(run func(ctx context.Context, holidayID int64)) *HolidayRepository_DeleteHoliday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *HolidayRepository_DeleteHoliday_Call) Return(_a0 error) *HolidayRepository_DeleteHoliday_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HolidayRepository_DeleteHoliday_Call) RunAndReturn(run func(context.Context, int64) error) *HolidayRepository_DeleteHoliday_Call {
	_c.Call.Return(run)
	return _c
}

// GetHolidays provides a mock function with given fields: ctx
func (_m *HolidayRepository) GetHolidays(ctx context.Context) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetHolidays")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]map[string]interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HolidayRepository_GetHolidays_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHolidays'
type HolidayRepository_GetHolidays_Call struct {
	*mock.Call
}

// GetHolidays is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HolidayRepository_Expecter) GetHolidays(ctx interface{}) *HolidayRepository_GetHolidays_Call {
	return &HolidayRepository_GetHolidays_Call{Call: _e.mock.On("GetHolidays", ctx)}
}

func (_c *HolidayRepository_GetHolidays_Call) Run(run func(ctx context.Context)) *HolidayRepository_GetHolidays_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *HolidayRepository_GetHolidays_Call) Return(_a0 []map[string]interface{}, _a1 error) *HolidayRepository_GetHolidays_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HolidayRepository_GetHolidays_Call) RunAndReturn(run func(context.Context) ([]map[string]interface{}, error)) *HolidayRepository_GetHolidays_Call {
	_c.Call.Return(run)
	return _c
}

// IsHoliday provides a mock function with given fields: ctx, date
func (_m *HolidayRepository) IsHoliday(ctx context.Context, date time.Time) (bool, error) {
	ret := _m.Called(ctx, date)

	if len(ret) == 0 {
		panic("no return value specified for IsHoliday")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) (bool, error)); ok {
		return rf(ctx, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) bool); ok {
		r0 = rf(ctx, date)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HolidayRepository_IsHoliday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsHoliday'
type HolidayRepository_IsHoliday_Call struct {
	*mock.Call
}

// IsHoliday is a helper method to define mock.On call
//   - ctx context.Context
//   - date time.Time
func (_e *HolidayRepository_Expecter) IsHoliday(ctx interface{}, date interface{}) *HolidayRepository_IsHoliday_Call {
	return &HolidayRepository_IsHoliday_Call{Call: _e.mock.On("IsHoliday", ctx, date)}
}

func (_c *HolidayRepository_IsHoliday_Call) Run(run func(ctx context.Context, date time.Time)) *HolidayRepository_IsHoliday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *HolidayRepository_IsHoliday_Call) Return(_a0 bool, _a1 error) *HolidayRepository_IsHoliday_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HolidayRepository_IsHoliday_Call) RunAndReturn(run func(context.Context, time.Time) (bool, error)) *HolidayRepository_IsHoliday_Call {
	_c.Call.Return(run)
	return _c
}

// NewHolidayRepository creates a new instance of HolidayRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHolidayRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *HolidayRepository {
	mock := &HolidayRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
