// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MyRequestsService is an autogenerated mock type for the MyRequestsService type
type MyRequestsService struct {
	mock.Mock
}

type MyRequestsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MyRequestsService) EXPECT() *MyRequestsService_Expecter {
	return &MyRequestsService_Expecter{mock: &_m.Mock}
}

// GetMyAllRequests provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MyRequestsService) GetMyAllRequests(ctx context.Context, userID int64, limit int, offset int) (map[string]interface{}, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetMyAllRequests")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) (map[string]interface{}, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int, int) map[string]interface{}); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MyRequestsService_GetMyAllRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMyAllRequests'
type MyRequestsService_GetMyAllRequests_Call struct {
	*mock.Call
}

// GetMyAllRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - limit int
//   - offset int
func (_e *MyRequestsService_Expecter) GetMyAllRequests(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MyRequestsService_GetMyAllRequests_Call {
	return &MyRequestsService_GetMyAllRequests_Call{Call: _e.mock.On("GetMyAllRequests", ctx, userID, limit, offset)}
}

func (_c *MyRequestsService_GetMyAllRequests_Call) Run(run func(ctx context.Context, userID int64, limit int, offset int)) *MyRequestsService_GetMyAllRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MyRequestsService_GetMyAllRequests_Call) Return(_a0 map[string]interface{}, _a1 error) *MyRequestsService_GetMyAllRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MyRequestsService_GetMyAllRequests_Call) RunAndReturn(run func(context.Context, int64, int, int) (map[string]interface{}, error)) *MyRequestsService_GetMyAllRequests_Call {
	_c.Call.Return(run)
	return _c
}

// GetMyRequests provides a mock function with given fields: ctx, userID, reqType
func (_m *MyRequestsService) GetMyRequests(ctx context.Context, userID int64, reqType string) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, userID, reqType)

	if len(ret) == 0 {
		panic("no return value specified for GetMyRequests")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) ([]map[string]interface{}, error)); ok {
		return rf(ctx, userID, reqType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) []map[string]interface{}); ok {
		r0 = rf(ctx, userID, reqType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userID, reqType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MyRequestsService_GetMyRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMyRequests'
type MyRequestsService_GetMyRequests_Call struct {
	*mock.Call
}

// GetMyRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - reqType string
func (_e *MyRequestsService_Expecter) GetMyRequests(ctx interface{}, userID interface{}, reqType interface{}) *MyRequestsService_GetMyRequests_Call {
	return &MyRequestsService_GetMyRequests_Call{Call: _e.mock.On("GetMyRequests", ctx, userID, reqType)}
}

func (_c *MyRequestsService_GetMyRequests_Call) Run(run func(ctx context.Context, userID int64, reqType string)) *MyRequestsService_GetMyRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string))
	})
	return _c
}

func (_c *MyRequestsService_GetMyRequests_Call) Return(_a0 []map[string]interface{}, _a1 error) *MyRequestsService_GetMyRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MyRequestsService_GetMyRequests_Call) RunAndReturn(run func(context.Context, int64, string) ([]map[string]interface{}, error)) *MyRequestsService_GetMyRequests_Call {
	_c.Call.Return(run)
	return _c
}

// NewMyRequestsService creates a new instance of MyRequestsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMyRequestsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MyRequestsService {
	mock := &MyRequestsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
