// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/ankita-advitot/rule_based_approval_engine/models"
)

// ReportRepository is an autogenerated mock type for the ReportRepository type
type ReportRepository struct {
	mock.Mock
}

type ReportRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportRepository) EXPECT() *ReportRepository_Expecter {
	return &ReportRepository_Expecter{mock: &_m.Mock}
}

// GetRequestStatusDistribution provides a mock function with given fields: ctx
func (_m *ReportRepository) GetRequestStatusDistribution(ctx context.Context) (map[string]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestStatusDistribution")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportRepository_GetRequestStatusDistribution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestStatusDistribution'
type ReportRepository_GetRequestStatusDistribution_Call struct {
	*mock.Call
}

// GetRequestStatusDistribution is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReportRepository_Expecter) GetRequestStatusDistribution(ctx interface{}) *ReportRepository_GetRequestStatusDistribution_Call {
	return &ReportRepository_GetRequestStatusDistribution_Call{Call: _e.mock.On("GetRequestStatusDistribution", ctx)}
}

func (_c *ReportRepository_GetRequestStatusDistribution_Call) Run(run func(ctx context.Context)) *ReportRepository_GetRequestStatusDistribution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReportRepository_GetRequestStatusDistribution_Call) Return(_a0 map[string]int, _a1 error) *ReportRepository_GetRequestStatusDistribution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportRepository_GetRequestStatusDistribution_Call) RunAndReturn(run func(context.Context) (map[string]int, error)) *ReportRepository_GetRequestStatusDistribution_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestsByTypeReport provides a mock function with given fields: ctx
func (_m *ReportRepository) GetRequestsByTypeReport(ctx context.Context) ([]models.RequestTypeReport, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestsByTypeReport")
	}

	var r0 []models.RequestTypeReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.RequestTypeReport, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.RequestTypeReport); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RequestTypeReport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportRepository_GetRequestsByTypeReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestsByTypeReport'
type ReportRepository_GetRequestsByTypeReport_Call struct {
	*mock.Call
}

// GetRequestsByTypeReport is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReportRepository_Expecter) GetRequestsByTypeReport(ctx interface{}) *ReportRepository_GetRequestsByTypeReport_Call {
	return &ReportRepository_GetRequestsByTypeReport_Call{Call: _e.mock.On("GetRequestsByTypeReport", ctx)}
}

func (_c *ReportRepository_GetRequestsByTypeReport_Call) Run(run func(ctx context.Context)) *ReportRepository_GetRequestsByTypeReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReportRepository_GetRequestsByTypeReport_Call) Return(_a0 []models.RequestTypeReport, _a1 error) *ReportRepository_GetRequestsByTypeReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportRepository_GetRequestsByTypeReport_Call) RunAndReturn(run func(context.Context) ([]models.RequestTypeReport, error)) *ReportRepository_GetRequestsByTypeReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewReportRepository creates a new instance of ReportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportRepository {
	mock := &ReportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
